Feat integration with sefaz
fazendatech/brafis pull request #11
Opened 2024-10-07 13:46 UTC by CayoPOliveira

2024-10-07 14:01 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @coderabbitai[bot])

___
*[`package.json` line 16 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271199:-O8bFfruAm6pkXL42A1a:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/package.json#L16)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Remova a dependência https do package.json.**

O módulo `https` é um módulo nativo do Node.js e não precisa ser instalado como um pacote separado. Incluí-lo como uma dependência no package.json é desnecessário e pode causar confusão.

Remova a seguinte linha do arquivo package.json:

```diff
-    "https": "1.0.0",
```

Você pode usar o módulo `https` diretamente em seu código importando-o com `import https from 'https';` sem precisar declará-lo como uma dependência.


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion

`````

</details>
<!-- suggestion_end -->

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 11 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271213:-O8bFjj50A6MuNZ0zGwn:b-wfvwi3) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/index.ts#L11)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Risco de segurança ao desabilitar a verificação de certificados TLS**

Definir `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` desativa a verificação de certificados TLS, o que pode expor a aplicação a ataques Man-in-the-Middle. Recomenda-se manter a verificação ativa para garantir a segurança nas comunicações SSL/TLS.

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

TODO Tentarei remover futuramente, por enquanto deixarei dessa forma
___
*[`src/dfe/nfe/index.ts` line 55 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271216:-O8bFxfX2driVjWmZv18:b-4h3lfl) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/index.ts#L55)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:hammer_and_wrench: Refactor suggestion_

**Evitar hardcode de certificados no código**

Os certificados CA estão sendo inseridos diretamente no código, o que não é uma prática recomendada. Isso pode dificultar a manutenção e introduzir riscos de segurança. É preferível carregar os certificados a partir de arquivos de configuração externos ou utilizar o repositório de certificados do sistema operacional.



Sugestão:

Considerar carregar os certificados CA de fontes externas ou ambientes de configuração.

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

TODO Futuramente tentarei remover também
___
*[`src/dfe/nfe/index.ts` line 60 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271228:-O8bG5Ss-ZxNj4jeHvcv:bjxg5bd) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/index.ts#L60)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Utilizar método HTTP POST para envio de XML**

O código está usando `axios.get` para enviar dados XML, mas o método adequado para enviar dados no corpo da requisição é `POST`. Recomenda-se alterar para `axios.post` e incluir o XML no corpo para garantir que os dados sejam enviados corretamente.



Sugestão de alteração:

```diff
- const response = await axios.get(url, {
+ const response = await axios.post(url, xml, {
```


> Committable suggestion was skipped due to low confidence.

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

LGTM por enquanto estou testando o get, depois mudarei para post
___
*[`src/dfe/nfe/index.ts` line 73 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271225:-O8bGSzj643p4t0LU90S:bb6ywmx) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/index.ts#L73)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Melhorar o tratamento de erros para depuração**

No bloco `catch`, uma mensagem genérica é lançada em caso de erro, o que pode dificultar a identificação do problema. Considere incluir detalhes do erro original na mensagem lançada para facilitar a depuração.



Sugestão de alteração:

```diff
- throw new Error("Erro ao enviar a requisição");
+ throw new Error(`Erro ao enviar a requisição: ${error.message}`);
```


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
    } catch (error) {
      // NOTE: This is a temporary solution to handle warnings
      if (errorHasMessage(error, "timeout")) {
        throw new Error(error.message);
      }
      throw new Error(`Erro ao enviar a requisição: ${error.message}`);
    }
`````

</details>
<!-- suggestion_end -->

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

LGTM
___
*[`src/dfe/nfe/index.ts` line 86 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271218:-O8bGbSQ1dynmXUzbSDf:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/index.ts#L86)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Inconsistência nos namespaces SOAP**

No objeto construído pelo `XMLBuilder`, há uma mistura de namespaces `soap12` e `soapenv`. Para evitar conflitos e garantir compatibilidade, é importante padronizar o uso de um único namespace.



Sugestão:

Padronizar todos os namespaces para `soap12` ou `soapenv` no objeto XML.

```diff
- "soap12:Envelope": {
+ "soapenv:Envelope": {
    "@_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
    "@_xmlns:xsd": "http://www.w3.org/2001/XMLSchema",
-   "@_xmlns:soap12": "http://www.w3.org/2003/05/soap-envelope",
+   "@_xmlns:soapenv": "http://www.w3.org/2003/05/soap-envelope",
    "soapenv:Body": {
      xmlData,
    },
  },
```


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
      "soapenv:Envelope": {
        "@_xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance",
        "@_xmlns:xsd": "http://www.w3.org/2001/XMLSchema",
        "@_xmlns:soapenv": "http://www.w3.org/2003/05/soap-envelope",
        "soapenv:Body": {
`````

</details>
<!-- suggestion_end -->

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Done.
___
*[`src/dfe/nfe/ufCode.ts` line 44 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271208:-O8bH-n07QFI83zA-hVM:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/ufCode.ts#L44)):*
<details><summary><i>Previously, coder [...]

2024-10-07 23:25 UTC, gabrieljablonski reviewed
https://gist.github.com/gabrieljablonski/6230abc79090174387abf8d1b809f272

Aplicar o `.patch` acima com `git apply brafis-11.patch`

Algumas considerações sobre o Bun. Apesar dele já estar relativamente maduro, existem algumas coisinhas ainda que ele deixa a desejar. Uma delas é a definição dos tipos.

[HTTP client – API | Bun Docs](https://bun.sh/docs/api/fetch#tls)

Existem diversas opções que o Bun já suporta internamente, que porém não estão refletidas nas definições de tipo. Esse patch cria uma função wrapper para que não precisemos nos preocupar com as definições de tipo atuais do `@types/bun` para a função `fetch`, que estão incompletas. Futuramente, é possível que façamos isso para mais implementações internas do Bun.

---

A respeito do uso de `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

Com o uso da cadeia de certificados `nfe-ca.pem` adicionada com o patch, os certificados dos WebServices passam a ser reconhecidos corretamente, não sendo mais necessário ignorar os erros.

A função `fetchWithTls` pode então ser utilizada da seguinte forma, resolvendo todos os problemas identificados até o momento:

```ts
const response = await fetchWithTls(url, {
  method: 'POST',
  body: xml,
  tls: {
    cert,
    key,
    ca: await loadNfeCa(),
  },
});
```

---

Dessa forma, favor remover referências do `node:https`, e remover o `axios` como dependência.

> Dismissed @CayoPOliveira and @coderabbitai[bot] from 7 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O8dGIzp22tko84lBL4C:byy9l30)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @coderabbitai[bot])

___
*[`src/dfe/nfe/index.ts` line 11 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271213:-O8dFjdFEpFPw-6c0NlE:b-tjaobq) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/index.ts#L11)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

TODO Tentarei remover futuramente, por enquanto deixarei dessa forma
</blockquote></details>

Resolvido com arquivo `nfe-ca.pem` passado para "nova" função `fetchWithTls`.
___
*[`src/dfe/nfe/index.ts` line 60 at r1](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1790271228:-O8dFxxHDNou0KHoetUv:bmek6l4) ([raw file](https://github.com/fazendatech/brafis/blob/319a7c63bc69ffc9a6c18278024e45b4cb34d42f/src/dfe/nfe/index.ts#L60)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

LGTM por enquanto estou testando o get, depois mudarei para post
</blockquote></details>

Não iremos usar o axios, em favor da "nova" função `fetchWithTls`.


<!-- Sent from Reviewable.io -->

2024-10-08 16:48 UTC, CayoPOliveira reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O8h11ZwEY8jmQBnN8el:bnfp4nl)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @coderabbitai[bot] and @gabrieljablonski)



<!-- Sent from Reviewable.io -->

2024-10-09 18:41 UTC, CayoPOliveira reviewed
+(review needed) 
-(work in progress) 

> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O8m_EgZ8moJxKPjTb6b:b3znvvr)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])

___
*[`src/dfe/nfe/index.ts` line 11 at r3](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1792224958:-O8mXfQR8e3mpZ9Mc7l5:b-odh0gr) ([raw file](https://github.com/fazendatech/brafis/blob/ddea3ae5c3f4516b01bb16cb2cc43b54a95efd5c/src/dfe/nfe/index.ts#L11)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Atenção: Configurações de segurança e depuração inadequadas**

Existem duas configurações potencialmente perigosas:

1. Desativar a verificação TLS (`NODE_TLS_REJECT_UNAUTHORIZED = "0"`) expõe a aplicação a ataques Man-in-the-Middle.
2. Habilitar o modo de depuração do Axios em produção pode vazar informações sensíveis.


Recomendações:
1. Remova a linha que desativa a verificação TLS.
2. Condicione o modo de depuração do Axios apenas para ambientes não produtivos.

```diff
- process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
- process.env.DEBUG = "axios";
+ if (process.env.NODE_ENV !== 'production') {
+   process.env.DEBUG = "axios";
+ }
```


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
if (process.env.NODE_ENV !== 'production') {
  process.env.DEBUG = "axios";
}
`````

</details>
<!-- suggestion_end -->

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Foi removida essa declaração
___
*[`src/dfe/nfe/index.ts` line 60 at r3](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1792224962:-O8mXquB3LyfL2t356YZ:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/ddea3ae5c3f4516b01bb16cb2cc43b54a95efd5c/src/dfe/nfe/index.ts#L60)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Correção necessária: Usar POST para envio de XML**

O método `request` está utilizando `axios.get` para enviar dados XML. O método HTTP apropriado para enviar dados no corpo da requisição é POST.


Recomendação:
Altere o método HTTP de GET para POST e inclua o XML no corpo da requisição.

```diff
- const response = await axios.get(url, {
+ const response = await axios.post(url, xml, {
    headers: {
      "Content-Type": "application/soap+xml; charset=utf-8",
    },
    httpsAgent: httpsAgent,
  });
```


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
      const response = await axios.post(url, xml, {
        headers: {
`````

</details>
<!-- suggestion_end -->

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 74 at r3](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1792224967:-O8m_BmBEgltJPMAzDyJ:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/ddea3ae5c3f4516b01bb16cb2cc43b54a95efd5c/src/dfe/nfe/index.ts#L74)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Melhorias necessárias no método `request`**

1. Os certificados CA estão hardcoded no código, o que dificulta a manutenção e pode representar um risco de segurança.
2. O tratamento de erros pode ser melhorado para fornecer mensagens mais específicas.


Recomendações:
1. Mova os certificados CA para um arquivo de configuração externo ou use o repositório de certificados do sistema operacional.
2. Melhore o tratamento de erros para fornecer mensagens mais específicas.

Exemplo de melhoria no tratamento de erros:

```diff
- throw new Error("Erro ao enviar a requisição");
+ throw new Error(`Erro ao enviar a requisição: ${error.message}`);
```


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
  async request(url: string, xml: string) {
    const { cert, key } = this.certificate.asPem();

    const httpsAgent = new https.Agent({
      cert: cert, // Certificado digital em formato PEM
      key: key, // Chave privada em formato PEM
      ca: [
        "-----BEGIN CERTIFICATE-----\r\nMIIHAjCCBOqgAwIBAgIJAJVIeKgiEmNTMA0GCSqGSIb3DQEBDQUAMIGYMQswCQYD\r\nVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDE9MDsGA1UECww0SW5zdGl0dXRv\r\nIE5hY2lvbmFsIGRlIFRlY25vbG9naWEgZGEgSW5mb3JtYWNhbyAtIElUSTE1MDMG\r\nA1UEAwwsQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3JhIFJhaXogQnJhc2lsZWlyYSB2\r\nMTAwHhcNMjAwMzEyMTkzMTQyWhcNMzIwNzAxMTIwMDU5WjCBjDELMAkGA1UEBhMC\r\nQlIxEzARBgNVBAoMCklDUC1CcmFzaWwxNTAzBgNVBAsMLEF1dG9yaWRhZGUgQ2Vy\r\ndGlmaWNhZG9yYSBSYWl6IEJyYXNpbGVpcmEgdjEwMTEwLwYDVQQDDChBdXRvcmlk\r\nYWRlIENlcnRpZmljYWRvcmEgZG8gU0VSUFJPIFNTTHYxMIICIjANBgkqhkiG9w0B\r\nAQEFAAOCAg8AMIICCgKCAgEA61jQVBX27GVzyZkJuyrEezqjBGdLSJDFRyGdwxbm\r\n8Ntr0AA8blhDaN5ASDOjqDESMA7xF38znfkZWBMLxJ3Ob0271W6G9bqgTwp/svhZ\r\ns91UcbZW6sB7gyxzMTGWLxcFMeBrurM0QpMVsp8hDH5Suv5rfP0YB9brz60k104u\r\nHG625rAcbRKHn7XsWJ1ZUQcwRzx1g0L1NlUKpsk0+eOAxTcVSVRTO33k+n6Gve83\r\n4MXMiG6Orved4isnEvQnl4AecCXOuUuM3vXZ+kdJGTpNy1HOy0coFdKCJSSCxU/y\r\nTbTiAiRJTc8rbvor3I7k7wR4ZDR8alDbW/Sbw1JEMtbQqMOXEOV7iEUIub0/uNT2\r\ng0oM4pu8DAxhIwy2YQCpjfCbzYu2bf1nabuOEQ2B4mFt/zgoxa5FLsM+0IjpCi8u\r\nz9RqLvYFo9pIy5BTi7JMkVfbgqcOv7vkQf3xF7sODdInCVRIbB0R6xpHm+bpitx9\r\nt5ip+Sf24QFlKbjy0gwVAnaEyf/iQF+t8qgcFBO65kyfH/2vs6iYg5TNhFKtjpqQ\r\niTyI7YkRkfTbLFdcgZbiRUUs5TFi0BkS4PAWupO1GgV9sJdk9gm3Z+KNZDgoAnu7\r\nCvhq1JXt6t7qO96WzBx9q9hi7T6eld1VFrV5Ya5kxM9Lgh+XcBDwfnDLI1Yoozbd\r\nMbkCAwEAAaOCAVcwggFTMIGtBgNVHSAEgaUwgaIwTwYGYEwBAYEJMEUwQwYIKwYB\r\nBQUHAgEWN2h0dHBzOi8vcmVwb3NpdG9yaW8uc2VycHJvLmdvdi5ici9kb2NzL2Rw\r\nY3NlcnByb3NzbC5wZGYwTwYGYEwBAgFpMEUwQwYIKwYBBQUHAgEWN2h0dHBzOi8v\r\ncmVwb3NpdG9yaW8uc2VycHJvLmdvdi5ici9kb2NzL2RwY3NlcnByb3NzbC5wZGYw\r\nQAYDVR0fBDkwNzA1oDOgMYYvaHR0cDovL2FjcmFpei5pY3BicmFzaWwuZ292LmJy\r\nL0xDUmFjcmFpenYxMC5jcmwwHwYDVR0jBBgwFoAUdPN+//yfU3rxfOurPqSm2hi6\r\nRWMwHQYDVR0OBBYEFK0WT0vxDL7CiqKFGNcNRiWTIuPNMA8GA1UdEwEB/wQFMAMB\r\nAf8wDgYDVR0PAQH/BAQDAgGGMA0GCSqGSIb3DQEBDQUAA4ICAQCDvWkOYakalAHB\r\n3ZcifI9yLyuTtjR8eYXlfDesYr7zMFVlmduVghCgueBMZxmht9BpLq9/ceBWu1q8\r\nsKge5oNNyySPmBJFe+CLjtB7Z1Ljk0Q/7A59lMCDZajojJlSEnH6pdhxA1JD58E0\r\ndGsom3SufuBWxdNfgsvpQNXDoKp48VlkyL4DKFCdJExtzuR5IlcQbB1FrmB5m2zo\r\nGG6j7UdoevmikIv01la+8kyn7CF5aNubRE0cfwxulik5LNM1uLIwfUVwYbbQiB8z\r\nbaLUOS2lU/pYr+seLQ7VBPHps/guGB9hKei/Df49KWjDVplu3+AuZhBHqiK533VJ\r\nf9Uwv3Rvx8FCobT54OCrAVfnFs8F6sM3dPh1u7AbW3Ddpeo4oBH5kBA0feLvLk7v\r\nmOnOq64oPMMoj+g6x0B0v7tGqOrNBZK486MaU/uaJi+omx+Le9EfyIz39BbRYGdV\r\nJvO/9P8vn5XnNXsmqziw08ENLjHcrro48tRm3YX0/BUgoitjMUqyzlKTgQ8UOpfi\r\nXeJzqvxvUMO/HgZK9aknN3WQXWXxIFG01OHsEOTd2Nddqbrth5qmZE+1IxwEH+ys\r\nQQzlV0pnPL5K0bRuPCqvH4Jr0CmwV2PqD6dkjI/Sy77XDkTP8adAuYjIEynBoQ0b\r\ntqY/0rJPT3dztepWAwRHhKbvO1yYkA==\r\n-----END CERTIFICATE-----\r\n",
        "-----BEGIN CERTIFICATE-----\r\nMIIGrDCCBJSgAwIBAgIJANLVi0S/gZNCMA0GCSqGSIb3DQEBDQUAMIGYMQswCQYD\r\nVQQGEwJCUjETMBEGA1UECgwKSUNQLUJyYXNpbDE9MDsGA1UECww0SW5zdGl0dXRv\r\nIE5hY2lvbmFsIGRlIFRlY25vbG9naWEgZGEgSW5mb3JtYWNhbyAtIElUSTE1MDMG\r\nA1UEAwwsQXV0b3JpZGFkZSBDZXJ0aWZpY2Fkb3 [...]

2024-10-09 21:00 UTC, gabrieljablonski requested changes
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, 1 of 4 files at r3, 6 of 8 files at r4, 6 of 6 files at r5, all commit messages.
> Dismissed @coderabbitai[bot] from 10 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: all files reviewed, 28 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])

___
*[`src/dfe/nfe/errors.ts` line 2 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mfGnF8oeP2pnXJTHV:-O8mfGnF8oeP2pnXJTHW:b2nhk2c) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/errors.ts#L2)):*
> ```XML
> import type { UF, Environment, WebService } from "./types.js";
> export class WebServiceNotFoundError extends Error {
> ```

NIT



_Suggestion:_
```XML
import type { UF, Environment, WebService } from "./types.ts";

export class WebServiceNotFoundError extends Error {
```
___
*[`src/dfe/nfe/errors.ts` line 8 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8miATvCvAZ1YqCocMF:-O8miATvCvAZ1YqCocMG:b4t0ii2) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/errors.ts#L8)):*
> ```XML
>     env: Environment,
>     contingencia: boolean,
>   ) {
> ```

Uso mais claro dessa forma.



_Suggestion:_
```XML
  constructor({
    uf,
    service,
    env,
    contingencia,
  }: { uf: UF; service: WebService; env: Environment; contingencia: boolean }) {
```
___
*[`src/dfe/nfe/errors.ts` line 30 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1794024090:-O8mim7aCwgQYq8lLqLt:bn42v8o) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/errors.ts#L30)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Melhore a segurança e legibilidade da mensagem de erro.**

A classe `ServiceRequestError` fornece informações abrangentes sobre falhas de requisição de serviço, o que é bom para depuração. No entanto, há algumas preocupações:

1. A mensagem de erro pode ficar muito longa, especialmente se o XML for grande.
2. Pode haver exposição de informações sensíveis no URL ou XML.



Sugiro as seguintes melhorias:

1. Limite o tamanho do XML na mensagem de erro.
2. Considere ocultar informações sensíveis do URL (como tokens de autenticação).
3. Armazene o XML completo em uma propriedade separada para depuração, em vez de incluí-lo na mensagem.

Exemplo de implementação:

```typescript
export class ServiceRequestError extends Error {
  public readonly xml: string;

  constructor(error: Error, url: string, xml: string) {
    const safeUrl = this.sanitizeUrl(url);
    const shortXml = xml.length > 100 ? xml.substring(0, 100) + '...' : xml;
    super(`Erro original: ${error.message}\nFalha na requisição para ${safeUrl}\nXML (resumido): ${shortXml}`);
    this.name = "ServiceRequestError";
    this.xml = xml;
  }

  private sanitizeUrl(url: string): string {
    // Implemente a lógica para remover informações sensíveis do URL
    // Por exemplo, removendo tokens de autenticação
    return url.replace(/token=[^&]+/, 'token=REDACTED');
  }
}
```

Essas mudanças melhorarão a segurança e a legibilidade da mensagem de erro, mantendo todas as informações necessárias para depuração.

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Considera essa sugestão de limitar o tamanho do XML no output.
___
*[`src/dfe/nfe/index.ts` line 12 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8miyeV15m2g_6RwCdv:-O8miyeV15m2g_6RwCdw:b-btmcvo) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L12)):*
> ```XML
> export interface NfeWebServicesOptions {
>   uf: UF;
>   env: Environment;
> ```

Considerando que talvez mudemos `Environment` -> `Ambiente`



_Suggestion:_
```XML
  ambiente: Ambiente;
```
___
*[`src/dfe/nfe/index.ts` line 28 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mjzY16RbVlZ2sFoNk:-O8mjzY16RbVlZ2sFoNl:bxz1s42) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L28)):*
> ```XML
>   private parser = new XMLParser({
>     ignoreAttributes: false,
>     removeNSPrefix: true,
> ```

Porque remover o prefixo?
___
*[`src/dfe/nfe/index.ts` line 35 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mjTQb5XomsOcG9x6y:-O8mjTQc42IJ-NWIoMFX:b-k04i6q) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L35)):*
> ```XML
>     this.env = options.env;
>     this.certificate = options.certificate;
>   }
> ```

Favor mover instanciações pra dentro do constructor.

Veja antes a [outra discussão](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mpT200FiVFQYeVyOF) sobre remover esses caras daqui.



_Suggestion:_
```XML
  private xmlBuilder: XMLBuilder;
  private xmlParser: XMLParser;

  constructor(options: NfeWebServicesOptions) {
    this.uf = options.uf;
    this.env = options.env;
    this.certificate = options.certificate;
    
    this.xmlBuilder = = new XMLBuilder({
      ignoreAttributes: false,
      attributeNamePrefix: "@_",
    });
    this.xmlParser = new XMLParser({
      ignoreAttributes: false,
      removeNSPrefix: true,
    });
  }
```
___
*[`src/dfe/nfe/index.ts` line 48 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mkVsmE6nQNsqRGVOZ:-O8mkVsn1EjEh9WkWD6B:b1hz7eo) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L48)):*
> ```XML
>           cert,
>           key,
>           ca: await loadNfeCa(),
> ```

Cria um atributo da classe pra armazenar a CA.

Acho que no futuro vamos achar uma forma melhor de guardar esse certificado no código, mas por enquanto carregar o arquivo ao instanciar o objeto (ao invés de a cada nova requisição) é bom o suficiente.
___
*[`src/dfe/nfe/index.ts` line 50 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1794024113:-O8ml0qb5XuEq11BFbK-:b-fhux9f) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L50)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:hammer_and_wrench: Refactor suggestion_

**Implementar timeout na requisição HTTP**

A função `fetchWithTls` não define um timeout, o que pode causar requisições pendentes indefinidamente se o serviço estiver indisponível ou lento.



Sugestão: Utilizar `AbortController` para implementar um timeout na requisição, garantindo que a aplicação não fique aguardando indefinidamente.

```typescript
const controller = new AbortController();
const timeout = setTimeout(() => {
  controller.abort();
}, 5000); // Timeout de 5 segundos

try {
  const response = await fetchWithTls(url, {
    method: "POST",
    headers: { "Content-Type": "application/soap+xml; charset=utf-8" },
    body: xml,
    tls: { cert, key, ca: await loadNfeCa() },
    signal: controller.signal,
  });

  if (!response.ok) {
    return undefined;
  }

  // ... código restante ...

} catch (error) {
  if (error.name === 'AbortError') {
    throw new Error('A requisição foi abortada devido ao timeout.');
  }
  throw new ServiceRequestError(error, url, xml);
} finally {
  clearTimeout(timeout);
}
```

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

o coelho tá certo aqui.

[HTTP client – API | Bun Docs](https://bun.sh/docs/api/fetch#fetching-a-url-with-a-timeout)

Vamos usar por enquanto o `AbortSignal.timeout`, mas no futuro talvez a gente exponha pro usuário poder cancelar os requests.

Não se esqueça de tratar o timeout.
___
*[`src/dfe/nfe/index.ts` line 63 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mlZIx5H56ehB141T8:-O8mlZIx5H56ehB141T9:b-9onz82) ([raw file](https://github.com/fazendatech/brafis/blob/93 [...]

2024-10-09 21:03 UTC, gabrieljablonski reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: all files reviewed, 30 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])

___
*[`src/dfe/nfe/index.ts` line 54 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n4btqAZnlprAeyzs8:-O8n4btqAZnlprAeyzs9:b-2hr96h) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L54)):*
> ```XML
>       if (!response.ok) {
>         return undefined;
>       }
> ```

A resposta veio com erro, mas eaí, fica por isso mesmo?
___
*[`src/dfe/nfe/index.ts` line 59 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n4gpo0bvmkIzMO4vF:-O8n4gpo0bvmkIzMO4vG:b-i0ea06) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L59)):*
> ```XML
>       if (!XMLValidator.validate(xmlData)) {
>         return undefined;
>       }
> ```

É mais eficiente dar um catch no erro do parser.

E seguindo a pergunta anterior, blz deu erro, mas e agora?


<!-- Sent from Reviewable.io -->

2024-10-10 16:18 UTC, CayoPOliveira reviewed
+(work in progress) 

> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O8rDNwa-R-gZOnNP8br:bcnppde)* status: all files reviewed, 28 unresolved discussions (waiting on @coderabbitai[bot] and @gabrieljablonski)

___
*[`src/dfe/nfe/errors.ts` line 8 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8miATvCvAZ1YqCocMF:-O8q2S7w3erkBSSGZGLg:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/errors.ts#L8)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Uso mais claro dessa forma.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/errors.ts` line 30 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1794024090:-O8q3Llo72bsMbbAn7Ng:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/errors.ts#L30)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Considera essa sugestão de limitar o tamanho do XML no output.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 12 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8miyeV15m2g_6RwCdv:-O8q9VMWBuPCrAB2o_ro:bsclaql) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L12)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Considerando que talvez mudemos `Environment` -> `Ambiente`
</blockquote></details>

Há outros tipos em inglês como AuthServer e WebService, eu acho que se for mudar para português os tipos, deveria mudar todos. O que você acha?

+(question/changes requested) 
___
*[`src/dfe/nfe/index.ts` line 28 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mjzY16RbVlZ2sFoNk:-O8q3tMqDYXuN-7X_Otw:bcefe32) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L28)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Porque remover o prefixo?
</blockquote></details>

Devido ao protocolo SOAP, ele permite diferentes prefixos, primeira vez que executei com uf 'DF' o soap tinha o padrão "soap:Envelope" e "soap:Body", em outro momento testei em outros estados e começou a dar problema, descobri que o soap voltava com "S:Envelope" e "S:Body", o prefixo pode mudar, mas o pós-fixo é sempre envelope e body.

Eu deveria comentar essa informação no código?
+(question/changes requested) 
___
*[`src/dfe/nfe/index.ts` line 35 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mjTQb5XomsOcG9x6y:-O8qCT4pCadBLVH3bM1l:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L35)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Favor mover instanciações pra dentro do constructor.

Veja antes a [outra discussão](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mpT200FiVFQYeVyOF) sobre remover esses caras daqui.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 48 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mkVsmE6nQNsqRGVOZ:-O8qDgx8DmP0KloPZJ5X:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L48)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Cria um atributo da classe pra armazenar a CA.

Acho que no futuro vamos achar uma forma melhor de guardar esse certificado no código, mas por enquanto carregar o arquivo ao instanciar o objeto (ao invés de a cada nova requisição) é bom o suficiente.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 50 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1794024113:-O8qGWtb8iJFyj1DOPpx:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L50)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

o coelho tá certo aqui.

[HTTP client – API | Bun Docs](https://bun.sh/docs/api/fetch#fetching-a-url-with-a-timeout)

Vamos usar por enquanto o `AbortSignal.timeout`, mas no futuro talvez a gente exponha pro usuário poder cancelar os requests.

Não se esqueça de tratar o timeout.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 54 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n4btqAZnlprAeyzs8:-O8qZjHf-ASEIGY0UyZP:bo0dtpi) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L54)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

A resposta veio com erro, mas eaí, fica por isso mesmo?
</blockquote></details>

Retorno undefined porque no serviço tento novamente usando o servidor de contingência
___
*[`src/dfe/nfe/index.ts` line 59 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n4gpo0bvmkIzMO4vF:-O8qLAdO5ibSXSaco4Vr:bbtt6zk) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L59)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

É mais eficiente dar um catch no erro do parser.

E seguindo a pergunta anterior, blz deu erro, mas e agora?
</blockquote></details>

O problema é que não tenho como filtrar os erros porque eles retornam apenas com a mensagem e elas variam muito sem fornecer uma documentação dos tipos, dá uma olhada no código do parser:
`https://github.com/NaturalIntelligence/fast-xml-parser/blob/master/src/xmlparser/XMLParser.js`
___
*[`src/dfe/nfe/index.ts` line 65 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mll-k78Yx0ld5KAw7:-O8qjC_4-o6vH-b2oalE:b6471it) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L65)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Não sei se gosto da ideia de encapsular um erro genérico. Se você não sabe qual erro você está tratando, deixa estourar pro usuário mesmo.

Veja que na implementação do `CertificateP12`, todos os erros tratados são conhecidos.

Depois a gente pode adicionar um modo debug que printa a URL e XML enviados pra ficar mais fácil de identificar problemas, mas esse wrapper aqui não ajuda de muita coisa.
</blockquote></details>

Done. Mudei para apenas dar throw no erro
___
*[`src/dfe/nfe/index.ts` line 89 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mpT200FiVFQYeVyOF:-O8qoG449EEWW9Rhf1UL:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L89)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Eu acho que a gente pode definir as funções de XML a parte do código da NF-e, pq a única parte relevante aqui é `nfeDadosMsg`.

O resto é padrão do SOAP, que vamos usar pra tudo, não só NF-e.

O que acha de mover as definições "base" para `src/utils/xml.ts`?

As funções seriam:

```ts
// Aqui, o generic `Obj` é só um placeholder pro compilador não chorar. Não muda nada na prática.
function build<Obj>(obj: Obj): string;

// Aqui, o generic é usado pro caller dessa função informar qual o output esperado pro objeto
function parse<Obj>(xml: string): Obj;
```

---

Pontos importantes:

- Instancie os objetos `builder` e `parser` dentro das funções, pois futuramente podemos precisar passar opções que serão repassadas para os construtores. O overhead dessas classes é muito baixo, então não precisa preocupar de estar instanciando uma nova pra cada request.
- Mova o header do xml e o  [...]

2024-10-15 13:30 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 4 of 17 files reviewed, 25 unresolved discussions (waiting on @CayoPOliveira, @coderabbitai[bot], and @gabrieljablonski)

___
*[`src/dfe/nfe/index.ts` line 123 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mneRf31-uTGoBtJGU:-O96GzcbBlwG7GVh6HA2:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L123)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Os servidores de contingência não são usados dessa forma automática.

Eles são habilitados manualmente pelo usuário do webservice, quando o SEFAZ publica um comunicado que autoriza o uso de contingência.

Extenda o `NfeWebServicesOptions` para receber a opção.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 125 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8moU2z21AEY78OgW4r:-O9FMwPTBdRFhz8RJb_Q:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/index.ts#L125)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Cadê a definição de tipo da resposta?

Dica, o método `request` provavelmente vai ter que aceitar o uso de generics.

```ts
async request<Body, Response>(url: string, body: Body): Promise<Response>;
```

Veja a [discussão](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mpT200FiVFQYeVyOF) sobre o xml builder/parser, que é extensão disso.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/types.d.ts` line 3 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mgFgt7d8Cy7BsevCl:-O96PNC33M8j6UIoLS4H:b1tfdn0) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/types.d.ts#L3)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Considerando que acabamos usando isso de chave em objetos, tipo

```ts
const webServices = {
  produção: ...
}
```

acabou ficando bem estranho com acento.

Opções:

1. Produção: `prod`/`producao`/`production`
2. Homologação: `hom`/`homologacao`/`homolog`

Pode escolher qualquer uma dessas, mas que seja consistente uma com a outra.
</blockquote></details>

Done Usei `producao` e `homologacao`
___
*[`src/dfe/nfe/types.d.ts` line 3 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mh0R_A11dbkp_JxHx:-O96Pjaq4HzdWcChP36H:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/types.d.ts#L3)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Essa parte da interface potencialmente será exposta na API, então é interessante ser mais "amigável" pros usuários.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/ufCode.ts` line 31 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8my2FnDT8ksKOBxLdN:-O96S1Uj5d3O90--jh4D:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/ufCode.ts#L31)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Defina um tipo `UFCode` igual ao `UF`, só que os códigos respectivos como string.

---

Comentário tangente, via de regra só defina um tipo como numérico se você for fazer operações numéricas com eles (existem exceções!!!).

Nesse caso, esses números nada mais são do que códigos/ids, então é melhor trabalhar com string mesmo.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/ufCode.ts` line 45 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8myg2nCL7gs0wo8sBm:-O96UFCdD5VUcFWL3faD:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/ufCode.ts#L45)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

1. Usar o novo tipo `UFCode`.
2. Como temos tipos definidos de forma rigorosa, podemos ignorar o caso do `undefined`.
3. Escrever TSDoc, essas funções serão expostas na API.

Veja tbm o que acha da simplificação do nome.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/ufCode.test.ts` line 40 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8mzpfn87eIrfRs2wX4:-O96VBCY56NLH9Wslyg6:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/ufCode.test.ts#L40)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Lembre-se desse mantra:

#### Testes bons testam o comportamento. Testes medíocres testam a saída.

Apesar do teste estar contemplando o comportamento esperado (retornar o código), está fazendo isso de forma exagerada.

Repetir o teste para cada UF não está testando novos comportamentos, então é redundante. Escolha uma UF e rode a função uma única vez.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/ufCode.test.ts` line 44 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n-fipBsZf5eRrLnwk:-O96VAqO0--xNA53BvD4:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/ufCode.test.ts#L44)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Chamar a função com uma UF inválida é comportamento indefinido no contexto do brafis, portanto esse teste não é relevante.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/ufCode.test.ts` line 47 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n0HjB2Zd9jBufTPSY:-O96VAb94S-anHFKTEaF:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/ufCode.test.ts#L47)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Favor aplicar mesmo raciocínio dos comentários anteriores.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/webServiceUrls.ts` line 15 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n1uR89PhOcNmYgtlS:-O96WTx13hiBvl-y2YQA:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/webServiceUrls.ts#L15)):*
> ```XML
>     };
>   };
> } = {
> ```

Done.
___
*[`src/dfe/nfe/webServiceUrls.ts` line 465 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n2PPy-Ukg-HXn8JoG:-O96Z5-Z9L12TAqAvTC9:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/webServiceUrls.ts#L465)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Retornar `""` aqui está inconsistente com o resto da lógica.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/webServiceUrls.ts` line 487 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O8n160u6FSCxe-RunDk:-O9BOX9e9ilS_uH5R267:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/webServiceUrls.ts#L487)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Maiores tragédias da humanidade:

1. Primeira guerra mundial
2. Segunda guerra mundial
3. `undefined` existir no JavaScript

Nunca jamais use o `undefined` explicitamente, ele só serve pra dar dor de cabeça.

Ainda preferia que aqui sempre retornasse string, mas pra ficar direitinho, teriamos que definir melhor o tipo do objetozão lá `webServices`.

Por enquanto só muda pra `null` mesmo. Aplica isso pra outros lugares que você retorna `undefined` (usa `?? null` no retorno).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-15 18:22 UTC, gabrieljablonski requested changes
> Reviewed 13 of 13 files at r6, all commit messages.
> Dismissed @coderabbitai[bot] from 8 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: all files reviewed, 37 unresolved discussions (waiting on @CayoPOliveira, @coderabbitai[bot], and @gabrieljablonski)

___
*[`src/dfe/nfe/errors.ts` line 14 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O9FvhfMESXDarza-j__:-O9FvhfMESXDarza-j_a:b5aa68g) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/errors.ts#L14)):*
> ```XML
>     this.name = "WebServiceNotFoundError";
>   }
> }
> ```

Eu tinha achado interessante a mensagem de erro especificar os parâmetros. Algum motivo ter removido?

Se adicionar de volta, passe os parâmetros por 1 objeto de arg apenas, ao invés de 4 args separados, pra ficar mais fácil na hora de invocar o erro.
___
*[`src/dfe/nfe/errors.ts` line 3 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Fus8H2fSJDPXiOreb:-O9Fus8IEYxch5RRo0JE:bp6eyxm) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L3)):*
> ```XML
> /**
>  * @description Não foi localizado a url do webservice.
>  */
> ```

Não colocamos descrições para os erros do certificado.

Acha que vale a pena ter mesmo? Se for o caso, vamos abrir uma issue e fazer o follow-up em outra PR para colocar nos erros dos certificados.
___
*[`src/dfe/nfe/errors.ts` line 12 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Fv9R7A1ZjP8p3Uka8:-O9Fv9R7A1ZjP8p3Uka9:bugkn95) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L12)):*
> ```XML
> 
> /**
>  * @description Especificar a UF para obter a URL do webservice.
> ```

NIT web service são duas palavras.

Muda ali no de cima tbm.



_Suggestion:_
```XML
 * @description Especificar a UF para obter a URL do web service.
```
___
*[`src/dfe/nfe/errors.ts` line 35 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Fw-J50L1BB1jD6cj4:-O9Fw-J65mMR0CMHBwfo:b-65baw8) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L35)):*
> ```XML
>  */
> export class ServiceRequestError extends Error {
>   constructor(error: Error, url: string, xml: string) {
> ```

Considera passar assim, com os parâmetros (além do `Error` original) em um arg só.



_Suggestion:_
```XML
  constructor(error: Error, extra: { url: string; xml: string }) {
```
___
*[`src/dfe/nfe/errors.ts` line 40 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Fx6b1BAhJ00ZGd-sb:-O9Fx6b1BAhJ00ZGd-sc:b-j2cchv) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L40)):*
> ```XML
>     );
>     this.name = "ServiceRequestError";
>   }
> ```

NIT

1. Opte por `slice` ao invés de `substring`
2. Use o símbolo `…` ao invés de 3 pontos quando possível
3. Typo em "Request"



_Suggestion:_
```XML
  constructor(error: Error, url: string, xml: string) {
    const truncatedXml = `${xml.slice(0, 100)}${xml.length > 100 ? '…' : ''}`,
    super(
      `Original Error: ${error.message}\nRequest to ${url} failed with XML:\n${truncatedXml}`,
    );
    this.name = "ServiceRequestError";
  }
```
___
*[`src/dfe/nfe/errors.ts` line 41 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1801201720:-O9FvJ9Y43xWioFeuCwB:b-6cagx2) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L41)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Correção de erro de digitação e sugestão de melhoria na classe `ServiceRequestError`.**

1. Há um erro de digitação na mensagem de erro: "Resquest" deve ser "Request".

2. Considere armazenar o XML completo em uma propriedade separada para facilitar a depuração:


```typescript
export class ServiceRequestError extends Error {
  public readonly fullXml: string;

  constructor(error: Error, url: string, xml: string) {
    super(
      `Original Error: ${error.message}\nRequest to ${url} failed with XML:\n${xml.length > 100 ? `${xml.substring(0, 100)}...` : xml}`,
    );
    this.name = "ServiceRequestError";
    this.fullXml = xml;
  }
}
```

Isso permitirá acesso ao XML completo quando necessário, mantendo a mensagem de erro concisa.

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Achei interessante a ideia do `fullXml`, útil para debug. Mas pode chamar só de `xml` o atributo.
___
*[`src/dfe/nfe/errors.ts` line 51 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1801201722:-O9G0Eul6iyQxyCWPTzU:bad74ls) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L51)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Correção na definição do nome do erro na classe `NfeStatusServicoError`.**

Há uma pequena discrepância entre o nome da classe e o nome do erro definido no construtor. Para manter a consistência, sugiro a seguinte correção:


```typescript
export class NfeStatusServicoError extends Error {
  constructor() {
    super("Unable to get status from the server's response");
    this.name = "NfeStatusServicoError"; // Corrigido de "NfeStatusServiceError"
  }
}
```

Isso garantirá que o nome do erro seja consistente com o nome da classe.

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

O correto aqui é mudar o nome da classe.



_Suggestion:_
```XML
export class NfeStatusServiceError extends Error {
  constructor() {
    super("Unable to get status from the server's response");
    this.name = "NfeStatusServiceError";
  }
}
```
___
*[`src/dfe/nfe/index.ts` line 17 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G15c59z7FbS4HfkwF:-O9G15c59z7FbS4HfkwG:bdfarjv) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L17)):*
> ```XML
> import { NfeConsultaCadastroError, NfeStatusServicoError } from "./errors.ts";
> 
> export interface NfeWebServicesOptions {
> ```

Essa interface será pública. Favor colocar descrição dos parâmetros, com atenção especial para os valores padrão de parâmetros opcionais.
___
*[`src/dfe/nfe/index.ts` line 25 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G0TmZ82XUkD34y7la:-O9G0TmZ82XUkD34y7lb:b2nhk2c) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L25)):*
> ```XML
>   statusServicoTimeout?: number;
>   consultaCadastroTimeout?: number;
> }
> ```

NIT



_Suggestion:_
```XML
  certificate: CertificateP12;
  contingency?: boolean;
  statusServicoTimeout?: number;
  consultaCadastroTimeout?: number;
}
```
___
*[`src/dfe/nfe/index.ts` line 25 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G0eeW3jS1FHInVVlN:-O9G0eeW3jS1FHInVVlO:b-neo0ah) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L25)):*
> ```XML
>   statusServicoTimeout?: number;
>   consultaCadastroTimeout?: number;
> }
> ```

Porque timeout por serviço?

1. Pense em casos de usos reais dessa classe. Quantos serviços diferentes geralmente eu vou chamar quando instanciar a classe?
2. Pense se tivéssemos 100 webservices.
___
*[`src/dfe/nfe/index.ts` line 36 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G1goIEw0iArCKFWyk:-O9G1goIEw0iArCKFWyl:b-vsyq5d) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L36)):*
> ```XML
>   private consultaCadastroTimeout?: number;
> 
>   private ca?: string;
> ```

Até faria sentido `ca` ser potencialmente vazio, mas vamos assumir que deve estar sempre [...]

2024-10-17 06:02 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 8 of 17 files reviewed, 26 unresolved discussions (waiting on @coderabbitai[bot] and @gabrieljablonski)

___
*[`src/dfe/nfe/errors.ts` line 14 at r5](https://reviewable.io/reviews/fazendatech/brafis/11#-O9FvhfMESXDarza-j__:-O9HntMWElc9v9QxPMYL:b-kfv1g7) ([raw file](https://github.com/fazendatech/brafis/blob/93f514dd86693753860a1a56ab814bbe00dde3f6/src/dfe/nfe/errors.ts#L14)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Eu tinha achado interessante a mensagem de erro especificar os parâmetros. Algum motivo ter removido?

Se adicionar de volta, passe os parâmetros por 1 objeto de arg apenas, ao invés de 4 args separados, pra ficar mais fácil na hora de invocar o erro.
</blockquote></details>

Tem um serviço que não precisa de UF e nem contingência, por causa dele fiquei na dúvida se mudava a mensagem de erro usando esses parâmetros como opcionais ou se criava um novo específico para ele. É o NFeDistribuicaoDFe que só possui no Ambiente Nacional (AN). Como você acha que fica melhor?

Update pós daily: Retornei os parâmetros a uma forma similar e atualizei o código da função getWebServiceUrl
___
*[`src/dfe/nfe/errors.ts` line 3 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Fus8H2fSJDPXiOreb:-O9HqHynAPV1-tidJkOr:b-tbq31y) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L3)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Não colocamos descrições para os erros do certificado.

Acha que vale a pena ter mesmo? Se for o caso, vamos abrir uma issue e fazer o follow-up em outra PR para colocar nos erros dos certificados.
</blockquote></details>

Quando fizemos os erros de certificado os nomes se tornaram auto-explicativos então não vi necessidade, porém  os nomes de erros para os web services acabaram ficando muito parecidos e achei melhor documentar, até para possível documentação geral dos erros futuramente, então acho válido fazer uma issue depois
___
*[`src/dfe/nfe/errors.ts` line 35 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Fw-J50L1BB1jD6cj4:-O9IDAUe5Pch3TEuRjyS:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L35)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Considera passar assim, com os parâmetros (além do `Error` original) em um arg só.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/errors.ts` line 41 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1801201720:-O9IVhAaE4A4PkuP0DET:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L41)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Achei interessante a ideia do `fullXml`, útil para debug. Mas pode chamar só de `xml` o atributo.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/errors.ts` line 51 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1801201722:-O9IVrezA0Kc6DPezCpn:b3yiqo9) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L51)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

O correto aqui é mudar o nome da classe.
</blockquote></details>

O nome do web service é `NfeStatusServico`, esse `serviço` acho que não é motivo de ser um web service, e sim para checar o status do serviço, eu troquei para `service` conforme a sugestão, mas aí gera uma inconsistência que os métodos seguem o padrão do serviço, então tem o método `statusServico` e `consultaCadastro`, por causa do consulta não acho que deveria mudar para `statusService` e também não acho que a classe de erro deveria mudar
___
*[`src/dfe/nfe/index.ts` line 25 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G0eeW3jS1FHInVVlN:-O9IYdg4CtfptUow4reD:bp6d9m3) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L25)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Porque timeout por serviço?

1. Pense em casos de usos reais dessa classe. Quantos serviços diferentes geralmente eu vou chamar quando instanciar a classe?
2. Pense se tivéssemos 100 webservices.
</blockquote></details>

Eu pensei em deixar opcional a definição de um timeout padrão para cada web service, mas ainda deixar de parâmetro opcional no método um timeout. Então a classe tem timeout padrão para cada web service, mas o usuário pode instanciar o web service e definir diferentes valores para os serviços que usará, ou passar o timeout no método.

Mas concordo que pode ser um pouco exagerado, removerei esses timeouts para a classe.

Update pós daily: Deixei apenas um timeout no construtor
___
*[`src/dfe/nfe/index.ts` line 38 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G1K7_3v7i8w7y4hOK:-O9IeWHW78ROiPh0PdY9:bb8fw91) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L38)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Pq `cUF` possivelmente `undefined`?

E pq `string`? `getUfCode` não retorna `string`.
</blockquote></details>

O undefined foi erro, arrumei já.

O tipo era string antes de criar o tipo `UFCode`, arrumei também.
___
*[`src/dfe/nfe/index.ts` line 64 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G2QB0DyhwCRva6x2t:-O9IgbOqEQ8i7MHcQywb:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L64)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

A chance é altíssima de precisarmos configurar outras coisas além do timeout, então favor criar uma interface similar ao do `fetch` para o response aqui.

Com o tempo vamos adicionando os parâmetros necessários.

Acho que é uma boa ideia já criar a interface para esse argumento, pq acho que fica bem pesada a declaração inline do exemplo abaixo. Fica só de referência mesmo.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 83 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G3v9U-iMh_4OPAWbu:-O9IlGky5T3R3MiadkI5:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L83)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Esse catch não tá fazendo nada. Se não for fazer nada com o erro interno, tira esse `catch/throw` que o error original já sobe sozinho.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 134 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G5JB-3k96mCQcNfxu:-O9NsZgCC7R-5OSZnTu1:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L134)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

É muuuuito raro que fazer isso aqui é uma boa ideia.

Uma função retornar dois tipos diferentes dependendo de uma condição é terrível em questão de usabilidade.

![image.png](https://files.reviewableusercontent.io/images/reviewable/21102974/a6w03BYhzH7tqae6utuQDzsn/image.png)

Na hora de usar o retorno, qual que é correto? Existem formas de fazer o TypeScript "coagir" o tipo de retorno de acordo com os argumentos, mas é meio chato de fazer, e a solução aqui é mais simples.

O tipo de retorno vai ser simplesmente assim:

```ts
interface NfeStatusResponse {
  status: 'ok' | 'paralisado-temp' | [...]

2024-10-17 06:03 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 8 of 17 files reviewed, 26 unresolved discussions (waiting on @coderabbitai[bot] and @gabrieljablonski)

___
*[`src/dfe/nfe/index.ts` line 17 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9G15c59z7FbS4HfkwF:-O9O3f3U5D59yc5OTEcj:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.ts#L17)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Essa interface será pública. Favor colocar descrição dos parâmetros, com atenção especial para os valores padrão de parâmetros opcionais.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-17 12:42 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 8 of 17 files reviewed, 37 unresolved discussions (waiting on @coderabbitai[bot] and @gabrieljablonski)

___
*[`src/index.ts` line 7 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1804165658:-O9PJdh05JQWr7J7R1GJ:bhzu8dc) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/index.ts#L7)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Adicione tratamento de erros para variáveis de ambiente ausentes.**

A inicialização do certificado agora usa variáveis de ambiente, o que é uma boa prática de segurança. No entanto, não há tratamento de erros para o caso de variáveis de ambiente ausentes.


Considere adicionar verificações e tratamento de erros:

```diff
-const certificate = await CertificateP12.fromFilepath({
-  filepath: process.env.TEST_CERTIFICATE_PATH ?? "",
-  password: process.env.TEST_CERTIFICATE_PASSWORD ?? "",
-});
+const certificatePath = process.env.TEST_CERTIFICATE_PATH;
+const certificatePassword = process.env.TEST_CERTIFICATE_PASSWORD;
+
+if (!certificatePath || !certificatePassword) {
+  throw new Error('Variáveis de ambiente TEST_CERTIFICATE_PATH e TEST_CERTIFICATE_PASSWORD são obrigatórias');
+}
+
+const certificate = await CertificateP12.fromFilepath({
+  filepath: certificatePath,
+  password: certificatePassword,
+});
```

Isso garantirá que o aplicativo falhe de forma mais previsível se as variáveis de ambiente necessárias não estiverem definidas.


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
const certificatePath = process.env.TEST_CERTIFICATE_PATH;
const certificatePassword = process.env.TEST_CERTIFICATE_PASSWORD;

if (!certificatePath || !certificatePassword) {
  throw new Error('Variáveis de ambiente TEST_CERTIFICATE_PATH e TEST_CERTIFICATE_PASSWORD são obrigatórias');
}

const certificate = await CertificateP12.fromFilepath({
  filepath: certificatePath,
  password: certificatePassword,
});
`````

</details>
<!-- suggestion_end -->

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Esse código por enquanto é teste, acho válido o apontamento, mas farei em outra PR dedicada ao index.ts
___
*[`src/dfe/nfe/index.ts` line 60 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1804165675:-O9PJsVuAc60saFwYPU0:b1qgb8h) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L60)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Validação do ambiente e código da UF**

A atribuição de `this.tpAmb` e `this.cUF` está considerando o ambiente corretamente. No entanto, é recomendável adicionar uma validação explícita para `this.env` para evitar configurações inválidas, conforme sugerido em comentários anteriores.



Sugestão de melhoria:

```typescript
if (this.env !== 'producao' && this.env !== 'homologacao') {
  throw new Error(`Ambiente inválido: ${this.env}`);
}
this.tpAmb = this.env === 'producao' ? '1' : '2';
```

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Como é controlado os tipos eu não acho necessário
___
*[`src/dfe/nfe/index.test.ts` line 52 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1804165659:-O9PK6MQ7mFsyl20zzs3:bseiixt) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.test.ts#L52)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:hammer_and_wrench: Refactor suggestion_

**Mover variáveis de URL para uma configuração separada**

As variáveis `urlStatusServico` e `urlConsultaCadastro` estão definidas diretamente no arquivo de teste. Para melhorar a manutenibilidade e reutilização, seria melhor movê-las para um arquivo de configuração separado ou um objeto de constantes.

Exemplo de implementação:

```typescript
// config/urls.ts
export const URLS = {
  STATUS_SERVICO: "https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx",
  CONSULTA_CADASTRO: "",
};

// No arquivo de teste:
import { URLS } from '../config/urls';

// ...

const { STATUS_SERVICO: urlStatusServico, CONSULTA_CADASTRO: urlConsultaCadastro } = URLS;
```

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Como são apenas duas urls acho desnecessário agora, futuramente ele deve apontar isso novamente e eu crio esse arquivo
___
*[`src/dfe/nfe/index.test.ts` line 107 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1804165660:-O9PKhAg4h-gDqu3gCj5:bdezlba) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.test.ts#L107)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Verificar URL vazia para consulta de cadastro**

O teste "Nfe get register consult success" está utilizando uma URL vazia (`urlConsultaCadastro`) para o mock. Isso pode levar a resultados inesperados ou falsos positivos no teste.

Sugestão:
1. Verifique se a URL correta para consulta de cadastro está definida.
2. Se a URL ainda não estiver disponível, considere adicionar um TODO comentário ou pular o teste até que a URL seja definida.

Exemplo:
```typescript
const urlConsultaCadastro = "https://nfe-homologacao.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro4.asmx"; // Substitua pela URL correta

// Ou, se a URL ainda não estiver disponível:
// TODO: Definir a URL correta para consulta de cadastro
// test.skip("Nfe get register consult success", async () => { ... });
```

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Done Fui mover para variável e não coloquei a url, apenas apaguei no código
___
*[`src/dfe/nfe/types.d.ts` line 136 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1804165671:-O9PL8HL25RFjHUpkS_L:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/types.d.ts#L136)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Correção na referência do tipo da propriedade `raw`**

Na interface `NfeStatusServicoResponse`, a propriedade `raw` é documentada como sendo de tipo `StatusRaw`, porém o tipo definido é `NfeStatusServicoRaw`. Para manter a consistência e evitar confusão, atualize a documentação para refletir o tipo correto.



Aplicar este ajuste na documentação:

```diff
- * @property {StatusRaw} [raw] (Opcional) - Resposta completa do serviço.
+ * @property {NfeStatusServicoRaw} [raw] (Opcional) - Resposta completa do serviço.
```


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
 * @description Retorno do serviço de consulta de status serviço.
 *
 * @property {"operando" | "paralisado-temporariamente" | "paralisado" | "outro"} [status] - Status do serviço.
 * @property {string} [description] - Descrição do status (xMotivo).
 * @property {NfeStatusServicoRaw} [raw] (Opcional) - Resposta completa do serviço.
 */
export interface NfeStatusServicoResponse {
  status: LiteralStringUnion<
    "operando" | "paralisado-temporariamente" | "paralisado" | "outro"
  >;
   [...]

2024-10-17 13:54 UTC, gabrieljablonski requested changes
> Reviewed 7 of 9 files at r7, 4 of 4 files at r8, all commit messages.
> Dismissed @CayoPOliveira and @coderabbitai[bot] from 22 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: all files reviewed, 33 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])

___
*[`src/dfe/nfe/errors.ts` line 3 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Fus8H2fSJDPXiOreb:-O9PKuqQ8zg6FADJd8KN:bxw16ts) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/errors.ts#L3)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

Quando fizemos os erros de certificado os nomes se tornaram auto-explicativos então não vi necessidade, porém  os nomes de erros para os web services acabaram ficando muito parecidos e achei melhor documentar, até para possível documentação geral dos erros futuramente, então acho válido fazer uma issue depois
</blockquote></details>

👍

[Escrever TSDoc das classes de erro do certificado · Issue #16 · fazendatech/brafis (github.com)](https://github.com/fazendatech/brafis/issues/16)
___
*[`src/dfe/nfe/errors.ts` line 21 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PLcsL-P_T8G6LYZNn:-O9PLcsL-P_T8G6LYZNo:beccjbn) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/errors.ts#L21)):*
> ```XML
>   public readonly xml: string;
>   constructor(error: Error, extra: { url: string; xml: string }) {
>     super(`${error.name}-${error.message}\nURL: ${extra.url}`);
> ```

Ainda acho interessante manter um pedacinho do XML na mensagem de erro, pode manter os 100 primeiros caracteres.

Facilita na hora de debugar.
___
*[`src/dfe/nfe/index.ts` line 30 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PTKeK9-VZIwp6nVxk:-O9PTKeK9-VZIwp6nVxl:bda4i9c) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L30)):*
> ```XML
>  * @property {boolean} [contingency] - Se True, será usado o servidor de contingência.
>  * @property {number} [timeout] - Timeout da requisição em ms, o valor padrão é 15 segundos.
>  */
> ```

NIT

Não tinha visto necessidade pra esse `@interface`. Vc viu algum motivo interessante? Se não, pode omitir.



_Suggestion:_
```XML
/**
 * @description Opções do `NfeWebServices`.
 *
 * @property {UF} uf - A unidade federativa (estado) para a NF-e.
 * @property {Environment} env - `"producao"` -> tpAmb = 1. "homologacao" -> tpAmb = 2.
 * @property {CertificateP12} certificate - O certificado P12 para autenticação.
 * @property {boolean} [contingency] - Habilitar uso do servidor de contingência.
 * @property {number} [timeout] - Timeout da requisição em ms, padrão 15000ms.
 */
```
___
*[`src/dfe/nfe/index.ts` line 48 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PU1G98I64IVMhHUIU:-O9PU1G98I64IVMhHUIV:b-tcwi4b) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L48)):*
> ```XML
>   private tpAmb: "1" | "2";
>   private cUF: UFCode;
>   private namespace: { "@_xmlns": string };
> ```

Acho que o tipo `{ "@_xmlns": string }` pode ser criado lá no `utils/xml.ts`, pq ele vai ser usado em outros lugares tbm.
___
*[`src/dfe/nfe/index.ts` line 105 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PXkyr14cRAzmKinwS:-O9PXkys485n5ni7GfJI:b2nhk2c) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L105)):*
> ```XML
>       .then((xml) => {
>         return parseSoap<NfeRequestResponse>(xml);
>       })
> ```

NIT



_Suggestion:_
```XML
      })
      .then((xml) => parseSoap<NfeRequestResponse>(xml))
```
___
*[`src/dfe/nfe/index.ts` line 108 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PXyzo25uKFIuMW2MM:-O9PXyzo25uKFIuMW2MN:b96dnk5) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L108)):*
> ```XML
>       .catch((error) => {
>         throw new ServiceRequestError(error, { url, xml: buildSoap(body) });
>       });
> ```

E se der timeout? 
___
*[`src/dfe/nfe/index.ts` line 112 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9P_rzd8H25eAkZ_F2H:-O9P_rzd8H25eAkZ_F2I:b2nhk2c) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L112)):*
> ```XML
> 
>   /**
>    * @description Consulta do status do serviço prestado pelo Portal da Secretaria de Fazenda Estadual.
> ```

NIT



_Suggestion:_
```XML
   * @description Consulta o status do serviço do SEFAZ correspondente a uma UF.
```
___
*[`src/dfe/nfe/index.ts` line 117 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PbbiK8paPvFaVPIvQ:-O9PbbiK8paPvFaVPIvR:b-is6vrj) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L117)):*
> ```XML
>    */
>   async statusServico(): Promise<NfeStatusServicoResponse> {
>     const reqResponse: { retConsStatServ: NfeStatusServicoRaw } =
> ```

Você acabou usando nomes diferentes pro objeto de resposta sem necessidade.

Vamos adotar assim de padrão. Altera no consulta cadastro tbm.



_Suggestion:_
```XML
    const response: { retConsStatServ: NfeStatusServicoRaw } =
```
___
*[`src/dfe/nfe/index.ts` line 131 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PY7bm4tf6edYSFku0:-O9PY7bm4tf6edYSFku1:bb8chjd) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L131)):*
> ```XML
>           },
>         },
>       });
> ```

Acho que vc chegou nuns 70% do uso de generics, então parabéns.

Mas amanhã a gente vai dar uma refatorada nessa parte pra ficar mais fácil de usar, com um padrão que vamos aplicar pra tudo que envolver request.

Segue a prévia:

```ts
export type NfeStatusServicoRequest = WithXmlns<{
  consStatServ: WithXmlnsVersao<{
    tpAmb: "1" | "2";
    cUF: UFCode;
    xServ: "STATUS";
  }>;
}>;

async statusServico(): Promise<NfeStatusServicoResponse> {
    const reqResponse = await this.request<
      NfeStatusServicoRequest,
      NfeStatusServicoResponseRaw
    >(this.getUrl("NfeStatusServico"), {
      timeout: this.timeout,
      body: {
        "@_xmlns": "http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4",
        consStatServ: {
          ...this.namespace,
          "@_versao": "4.00",
          tpAmb: this.tpAmb,
          cUF: this.cUF,
          xServ: "STATUS",
        },
      },
    });
  ...
```
___
*[`src/dfe/nfe/index.ts` line 133 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PZ4Am-Wwa9_3t36KH:-O9PZ4AnAEvuPnjSWDdo:b2nhk2c) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L133)):*
> ```XML
>       });
> 
>     let status = "outro";
> ```

NIT



_Suggestion:_
```XML
    let status = "desconhecido";
```
___
*[`src/dfe/nfe/index.ts` line 140 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PZ9Yy3hxpTUW8kox3:-O9PZ9Yz4dKdadVvvPTN:b-ek1xdr) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L140)):*
> ```XML
>     } else if (reqResponse.retConsStatServ.cStat === "109") {
>       status = "paralisado";
>     }
> ```

Aqui é uma das situações que vale a pena abrir outra variável.

Mas também tem a opção de usar um objeto pra ficar mais clean.

Veja oq acha melhor, e aplique nos outros lugares tbm.

```ts
    const statusMap: Record<string, NfeConsultaCadastroResponse["status"]> = {
      "107": "operando",
      "108": "paralisado-temporariamente",
      "109": "paralisado",
    };
    const status =
      statusMap[reqResponse.retConsStatServ.cStat ?? ""] ?? "outro";
```



_Suggestion:_
```XML
    let status = "o [...]

2024-10-17 13:55 UTC, gabrieljablonski reviewed
> Dismissed @CayoPOliveira from a discussion.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: all files reviewed, 32 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])



<!-- Sent from Reviewable.io -->

2024-10-17 14:32 UTC, CayoPOliveira commented
*[`src/dfe/nfe/index.test.ts` line 31 at r6](https://reviewable.io/reviews/fazendatech/brafis/11#-O9GKEXV-ba4rRYKTh4V:-O9Psie1-qK5pObueir2:b-btakgt) ([raw file](https://github.com/fazendatech/brafis/blob/3baad230d8dc851c8b613ac4c52cc22a4b041f4e/src/dfe/nfe/index.test.ts#L31)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Você fez um teste de erro genérico.

O timeout tem que ser testado separado.
</blockquote></details>

O timeout cai no mesmo erro porque não tem um catch específico.


<!-- Sent from Reviewable.io -->

2024-10-18 03:47 UTC, CayoPOliveira reviewed
-(question/changes requested)  +(review needed) 

> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O9SCgF16z7qhFLGWuj_:b7ilc9i)* status: all files reviewed, 21 unresolved discussions (waiting on @CayoPOliveira, @coderabbitai[bot], and @gabrieljablonski)

___
*[`src/dfe/nfe/errors.ts` line 21 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PLcsL-P_T8G6LYZNn:-O9SDF4E1e4vB4UkE9hO:b-b1xmln) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/errors.ts#L21)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Ainda acho interessante manter um pedacinho do XML na mensagem de erro, pode manter os 100 primeiros caracteres.

Facilita na hora de debugar.
</blockquote></details>

Os 100 primeiros caracteres não chega nem a sair do soap. Então sempre aparecerá na mensagem a declaração xml e o comecinho do soap. Por essa razão achei melhor tirar ele mesmo. Vou adicionar novamente e me fala o que acha.
___
*[`src/dfe/nfe/index.ts` line 48 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PU1G98I64IVMhHUIU:-O9SGrkY6X887kuM2r0w:bb6un1j) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L48)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Acho que o tipo `{ "@_xmlns": string }` pode ser criado lá no `utils/xml.ts`, pq ele vai ser usado em outros lugares tbm.
</blockquote></details>

Done
___
*[`src/dfe/nfe/index.ts` line 108 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PXyzo25uKFIuMW2MM:-O9SSqYA-4mlpCcPgcyO:b-vu5v3l) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L108)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

E se der timeout?
</blockquote></details>

Done Agora ele deixa passar o timeout direto
___
*[`src/dfe/nfe/index.ts` line 117 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PbbiK8paPvFaVPIvQ:-O9SUZYb3wuD5bK2feXH:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L117)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Você acabou usando nomes diferentes pro objeto de resposta sem necessidade.

Vamos adotar assim de padrão. Altera no consulta cadastro tbm.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 131 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PY7bm4tf6edYSFku0:-O9SY8-T06TgcISMZArM:bb7462z) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L131)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Acho que vc chegou nuns 70% do uso de generics, então parabéns.

Mas amanhã a gente vai dar uma refatorada nessa parte pra ficar mais fácil de usar, com um padrão que vamos aplicar pra tudo que envolver request.

Segue a prévia:

```ts
export type NfeStatusServicoRequest = WithXmlns<{
  consStatServ: WithXmlnsVersao<{
    tpAmb: "1" | "2";
    cUF: UFCode;
    xServ: "STATUS";
  }>;
}>;

async statusServico(): Promise<NfeStatusServicoResponse> {
    const reqResponse = await this.request<
      NfeStatusServicoRequest,
      NfeStatusServicoResponseRaw
    >(this.getUrl("NfeStatusServico"), {
      timeout: this.timeout,
      body: {
        "@_xmlns": "http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4",
        consStatServ: {
          ...this.namespace,
          "@_versao": "4.00",
          tpAmb: this.tpAmb,
          cUF: this.cUF,
          xServ: "STATUS",
        },
      },
    });
  ...
```
</blockquote></details>

TODO
___
*[`src/dfe/nfe/index.ts` line 133 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PZ4Am-Wwa9_3t36KH:-O9SYQZP3CQrsywQOdFF:b7rhdnz) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L133)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

NIT
</blockquote></details>

Usei `sem-sucesso` porque é um código apenas não mapeado por não ser sucesso, o que acha?
___
*[`src/dfe/nfe/index.ts` line 140 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PZ9Yy3hxpTUW8kox3:-O9SYbawCSi-6lOGY1M3:b-u72plp) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L140)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Aqui é uma das situações que vale a pena abrir outra variável.

Mas também tem a opção de usar um objeto pra ficar mais clean.

Veja oq acha melhor, e aplique nos outros lugares tbm.

```ts
    const statusMap: Record<string, NfeConsultaCadastroResponse["status"]> = {
      "107": "operando",
      "108": "paralisado-temporariamente",
      "109": "paralisado",
    };
    const status =
      statusMap[reqResponse.retConsStatServ.cStat ?? ""] ?? "outro";
```
</blockquote></details>

Done usei outro objeto
___
*[`src/dfe/nfe/index.ts` line 155 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9P_Ww4BCaZO9Pj4Mp-:-O9SZ1zq5Pc3B_DWnaYF:bb7462z) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L155)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Vamos aplicar as mesmas ideias do status serviço.
</blockquote></details>

TODO
___
*[`src/dfe/nfe/index.ts` line 174 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PcqRU9mc0e-9FfcMa:-O9SZMZq7_wh0lDnT-mx:b-lj71rl) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L174)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Olha oq acontece quando não se usa os tipos corretamente.

`"uma-ocorrência"` não existe.

Use a lógica lá do `statusServico` pra melhorar aqui.

```ts
    const statusMap: Record<string, NfeConsultaCadastroResponse["status"]> = {
      "107": "operando",
      "108": "paralisado-temporariamente",
      "109": "paralisado",
    };
```
</blockquote></details>

Não entendi oque você quis dizer com não existir `"uma-ocorrência"`, se for pelo acento já removi.
___
*[`src/dfe/nfe/index.ts` line 71 at r8](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1804720342:-O9SQqNk86Ov0xu4_m0p:blxdd1c) ([raw file](https://github.com/fazendatech/brafis/blob/8f6b6b0f0fdf24a46e79df025e3eaf043340bbe3/src/dfe/nfe/index.ts#L71)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Adicionar tratamento de erros no método getCa**

O método `getCa` implementa o carregamento preguiçoso do certificado CA, o que é uma boa prática para performance. No entanto, não há tratamento de erros caso a função `loadNfeCa()` falhe.

Sugestão: Adicione um bloco try-catch para lidar com possíveis erros durante o carregamento do certificado CA.

```typescript
private async getCa(): Promise<string> {
  if (!this.ca) {
    try {
      this.ca = await loadNfeCa();
    } catch (error) {
      throw new Error(`Falha ao carregar o certificado CA: ${error.message}`);
    }
  }
  return this.ca;
}
```

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Não é necessário, o erro irá ser informado como ServiceRequestError
___
*[`src/dfe/nfe/index.test.ts` line 115 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PdEga6T5ANlHxahK6:-O9S_EFIB6jUAUFvcU8s:bgm7qgh) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/ [...]

2024-10-18 12:30 UTC, gabrieljablonski requested changes
-(review needed) +(question/changes requested) 

> Reviewed 5 of 9 files at r9, all commit messages.
> Dismissed @coderabbitai[bot] from 11 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O9Uat1o5FtN-kNp8pTh:b-2dq2iu)* status: 14 of 18 files reviewed, 16 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])

___
*[`src/dfe/nfe/errors.ts` line 21 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PLcsL-P_T8G6LYZNn:-O9UXaqyD6Soy4ZxrsJl:b6w6xsd) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/errors.ts#L21)):*
> Os 100 primeiros caracteres não chega nem a sair do soap

ah vamos tirar então
___
*[`src/dfe/nfe/index.ts` line 133 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PZ4Am-Wwa9_3t36KH:-O9UYv2Y6bzyzEbtdYwK:b2nhzrf) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L133)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

Usei `sem-sucesso` porque é um código apenas não mapeado por não ser sucesso, o que acha?
</blockquote></details>

blz
___
*[`src/dfe/nfe/index.ts` line 140 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PZ9Yy3hxpTUW8kox3:-O9UYxfQDzsL0Oj3H-2n:bwfv9ql) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L140)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

Done usei outro objeto
</blockquote></details>

Não ficou legal ter essa função separada. Vamos fazer a relação dos status dentro de cada método mesmo.
___
*[`src/dfe/nfe/index.ts` line 174 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PcqRU9mc0e-9FfcMa:-O9UZFWq4FO7eCaH0rcU:bmh8yt) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L174)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

Não entendi oque você quis dizer com não existir `"uma-ocorrência"`, se for pelo acento já removi.
</blockquote></details>

Sim, era o acento.
___
*[`src/dfe/nfe/index.ts` line 22 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UXk05DiCwmLzjszsw:-O9UXk05DiCwmLzjszsx:b2nhk2c) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/index.ts#L22)):*
> ```XML
> 
> /**
>  * @description Opções do "NfeWebServices".
> ```

NIT



_Suggestion:_
```XML
 * @description Opções do `NfeWebServices`.
```
___
*[`src/dfe/nfe/types.d.ts` line 193 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UZcfb8_wsg65xl8u6:-O9UZcfb8_wsg65xl8u7:b6u4dq1) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L193)):*
> ```XML
>  * @description Opções para configurar o web service de consulta cadastro.
>  *
>  * @property {boolean} [raw] - Se verdadeiro, a resposta terá o parâmetro raw com a resposta completa do serviço.
> ```

Atualizar descrição.
___
*[`src/dfe/nfe/types.d.ts` line 204 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UZi_OEu81Cr5u-P_i:-O9UZi_OEu81Cr5u-P_j:b6u4dq1) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L204)):*
> ```XML
>  * @description Retorno do serviço consulta cadastro.
>  *
>  * @property {NfeConsultaCadastroRaw} [raw] - Resposta completa do serviço, se passado o parâmetro raw.
> ```

Atualizar descrição.
___
*[`src/dfe/nfe/types.d.ts` line 236 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UZmbYAf_PJCIAiMZT:-O9UZmbYAf_PJCIAiMZU:bb31is) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L236)):*
> ```XML
>   xMun?: string;
>   CEP?: string;
> }
> ```

Campos são opcionais mesmo?
___
*[`src/dfe/nfe/types.d.ts` line 303 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1805815327:-O9U_E6x4EaU7arT94Ms:b-vnss6m) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L303)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:warning: Potential issue_

**Corrigir a sintaxe do tipo de 'infCad' para o formato correto de array**

A declaração `infCad: Array[InfCad];` apresenta uma sintaxe incorreta em TypeScript. O formato correto para definir um array de `InfCad` é `InfCad[]` ou `Array<InfCad>`.



Aplicar esta correção:

```diff
 export interface InfCons {
   verAplic: string;
   cStat: CodStats;
   xMotivo: string;
   UF: string;
   IE: string;
   CNPJ: string;
   CPF: string;
   dhCons: string;
   cUF: string;
-  infCad: Array[InfCad];
+  infCad: InfCad[];
 }
```


<!-- suggestion_start -->
<details>
<summary>📝 Committable suggestion</summary>

> ‼️ **IMPORTANT**
> Carefully review the code before committing. Ensure that it accurately replaces the highlighted code, contains no missing lines, and has no issues with indentation. Thoroughly test & benchmark the code to ensure it meets the requirements.

`````suggestion
export interface InfCons {
  verAplic: string;
  cStat: CodStats;
  xMotivo: string;
  UF: string;
  IE: string;
  CNPJ: string;
  CPF: string;
  dhCons: string;
  cUF: string;
  infCad: InfCad[];
}
`````

</details>
<!-- suggestion_end -->

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

^

Opta por `[]` pra indicar array. Algumas situações até é bom usar o `Array`, mas a sintaxe correta é `Array<...>`
___
*[`src/dfe/nfe/webServiceUrls.ts` line 74 at r8](https://reviewable.io/reviews/fazendatech/brafis/11#-O9Phvuw94GBYkvSqn04:-O9U_hUE-T7jdYHbEOOX:b-obmuvb) ([raw file](https://github.com/fazendatech/brafis/blob/8f6b6b0f0fdf24a46e79df025e3eaf043340bbe3/src/dfe/nfe/webServiceUrls.ts#L74)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

Não entendi
</blockquote></details>

ia falar alguma coisa, desisti, e esqueci de apagar o comentário kkkk


<!-- Sent from Reviewable.io -->

2024-10-18 12:31 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 13 of 18 files reviewed, 17 unresolved discussions (waiting on @coderabbitai[bot] and @gabrieljablonski)

___
*[`src/dfe/nfe/index.ts` line 169 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1805815318:-O9UZqXVBCUYR1tO0RKE:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/index.ts#L169)):*
<details><summary><i>Previously, coderabbitai[bot] wrote…</i></summary><blockquote>

_:hammer_and_wrench: Refactor suggestion_

**Aprovado com sugestão de melhoria no tratamento de erros**

Os métodos `statusServico` e `consultaCadastro` estão bem implementados, fazendo bom uso do método `request` e tratando as respostas de forma apropriada.

Sugestão de melhoria:

Considere adicionar uma verificação adicional para garantir que a resposta contenha os campos esperados antes de acessá-los. Por exemplo, no método `consultaCadastro`:

```typescript
return {
  status: response.retConsCad.infCons?.cStat 
    ? getInfoStatus(response.retConsCad.infCons.cStat)
    : 'erro_desconhecido',
  description: response.retConsCad.infCons?.xMotivo ?? "Resposta inválida do servidor",
  raw: response.retConsCad,
};
```

Isso ajudará a evitar erros de runtime caso a resposta do servidor não contenha a estrutura esperada.

<!-- This is an auto-generated comment by CodeRabbit -->
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-18 14:38 UTC, CayoPOliveira commented
*[`src/dfe/nfe/index.ts` line 22 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UXk05DiCwmLzjszsw:-O9V30UL10xwDxPe5xeV:b-yqqh06) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/index.ts#L22)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

NIT
</blockquote></details>

Upvote


<!-- Sent from Reviewable.io -->

2024-10-18 14:40 UTC, CayoPOliveira commented
*[`src/dfe/nfe/index.test.ts` line 115 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PdEga6T5ANlHxahK6:-O9V3X361qzuO7BWPL6t:b-jlakdy) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.test.ts#L115)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

Checa se está da forma correta, porfavor.
</blockquote></details>

upvote


<!-- Sent from Reviewable.io -->

2024-10-18 14:40 UTC, CayoPOliveira commented
*[`src/dfe/nfe/types.d.ts` line 193 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UZcfb8_wsg65xl8u6:-O9V3aXf64VXogvPaiL5:b-jlakdy) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L193)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Atualizar descrição.
</blockquote></details>

upvote


<!-- Sent from Reviewable.io -->

2024-10-18 14:43 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 5 of 19 files reviewed, 14 unresolved discussions (waiting on @CayoPOliveira, @coderabbitai[bot], and @gabrieljablonski)

___
*[`src/dfe/nfe/index.ts` line 131 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PY7bm4tf6edYSFku0:-O9V39WX8Bl_tE_LEKQF:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L131)):*
<details><summary><i>Previously, CayoPOliveira (Cayo P. R. Oliveira) wrote…</i></summary><blockquote>

TODO
</blockquote></details>

Done.
___
*[`src/dfe/nfe/index.ts` line 174 at r7](https://reviewable.io/reviews/fazendatech/brafis/11#-O9PcqRU9mc0e-9FfcMa:-O9V3N9EBvq6mWbTGekd:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/35516e319362ea52f4d4300c10ff6d77354bb4aa/src/dfe/nfe/index.ts#L174)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Sim, era o acento.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/types.d.ts` line 204 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UZi_OEu81Cr5u-P_i:-O9V3k2cCdZKu9mYBNTg:b-jlakdy) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L204)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Atualizar descrição.
</blockquote></details>

upvote
___
*[`src/dfe/nfe/types.d.ts` line 236 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#-O9UZmbYAf_PJCIAiMZT:-O9V3mpq4PmR7HA41hJY:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L236)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Campos são opcionais mesmo?
</blockquote></details>

Done.
___
*[`src/dfe/nfe/types.d.ts` line 303 at r9](https://reviewable.io/reviews/fazendatech/brafis/11#gh-1805815327:-O9V3tViBPGEGhG49Axd:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/630e145f7c389eac741ca36460538e8d155fcc00/src/dfe/nfe/types.d.ts#L303)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

^

Opta por `[]` pra indicar array. Algumas situações até é bom usar o `Array`, mas a sintaxe correta é `Array<...>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-18 14:44 UTC, gabrieljablonski reviewed
> Dismissed @CayoPOliveira and @coderabbitai[bot] from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 5 of 19 files reviewed, 5 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])



<!-- Sent from Reviewable.io -->

2024-10-18 14:45 UTC, gabrieljablonski reviewed
> Dismissed @coderabbitai[bot] from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 5 of 19 files reviewed, all discussions resolved (waiting on @CayoPOliveira)



<!-- Sent from Reviewable.io -->

2024-10-18 14:46 UTC, gabrieljablonski reviewed
-(work in progress) -(question/changes requested) +(approved for merge) 

> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O9V4tzd3sQiO7ceVpsv:bkub9me)* status: 5 of 19 files reviewed, all discussions resolved (waiting on @CayoPOliveira)



<!-- Sent from Reviewable.io -->

2024-10-18 14:46 UTC, gabrieljablonski submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11#-:-O9V4za8BvhFAP3tx9Wm:bnfp4nl)* status: 5 of 19 files reviewed, all discussions resolved (waiting on @CayoPOliveira and @gabrieljablonski)



<!-- Sent from Reviewable.io -->

2024-10-18 14:57 UTC, gabrieljablonski approved these changes
> Reviewed 1 of 9 files at r12.
> Dismissed @coderabbitai[bot] from 7 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/11)* status: 5 of 19 files reviewed, all discussions resolved (waiting on @CayoPOliveira)



<!-- Sent from Reviewable.io -->

2024-10-18 14:58 UTC, merged