Feat create NFe
fazendatech/brafis pull request #29
Opened 2024-10-30 04:28 UTC by CayoPOliveira

2024-11-12 00:45 UTC, gabrieljablonski requested changes
-(review needed) +(question/changes requested) 

> Reviewed 2 of 8 files at r1, 9 of 12 files at r2, 3 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> Dismissed @coderabbitai[bot] from 34 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/29#-:-OBSpCgv-m_FepLr04Rb:b-bj7auo)* status: all files reviewed, 49 unresolved discussions (waiting on @CayoPOliveira)

___
*[`src/dfe/nfe/schemas/groupE.ts` line 38 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSgvDxDniqmNTWJYEx:-OBSgvDy40AibHeiXXxW:b-7woscz) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupE.ts#L38)):*
> Validar?

Não.



_Suggestion:_
```XML
    ISUF: zCustom.string.range(8, 9).optional().describe("E18"),
```
___
*[`src/dfe/nfe/schemas/groupI.ts` line 12 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSjKyx4FdRI2CYHzSF:-OBSjKyx4FdRI2CYHzSG:b-yesycj) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupI.ts#L12)):*
> ```XML
>   .object({
>     cProd: zCustom.string.range(1, 60).describe("I02"),
>     cEAN: zCustom.string.range(8, 14).describe("I03"),
> ```

A documentação diz que 0 caracteres também é um cEAN válido (e na verdade são tamanho específicos, não 8~14).

Acho que aqui é melhor validar com `refine()` (0/8/12/13/14).
___
*[`src/dfe/nfe/schemas/groupI.ts` line 25 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSifM643xNK07-7Uod:-OBSifM643xNK07-7Uoe:b5f8yzx) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupI.ts#L25)):*
> ```XML
>       .min(8)
>       .max(10)
>       .refine((value) => value.length !== 9)
> ```

Entendi, mas veja se consegue pensar numa validação melhor aqui.

Talvez com regex resolve mais fácil. Algo tipo `\d{8}(\d{2})?`. Ou faça igual o do cEAN com `refine()` mesmo.



_Code quote:_
```XML
      .min(8)
      .max(10)
      .refine((value) => value.length !== 9)
```
___
*[`src/dfe/nfe/schemas/groupE.ts` line 17 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSgPp-AWgrdHWE5uwv:-OBSgPp0AuT87pmmINQw:b7n29oc) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupE.ts#L17)):*
> ```XML
>     UF: zUf().or(z.literal("EX")).describe("E12"), // "EX" - Operações no exterior
>     CEP: zCustom.string.numeric().length(8).optional().describe("E13"),
>     cPais: zCustom.string.numeric().min(2).max(4).optional().describe("E14"), // TODO: Validar - utilizar a Tabela do BACEN (Seção 8.3 do MOC – Visão Geral, Tabela de UF, Município e País).
> ```

Não faremos essa validação.



_Suggestion:_
```XML
    cPais: zCustom.string.numeric().min(2).max(4).optional().describe("E14"),
```
___
*[`src/dfe/nfe/schemas/groupE.ts` line 25 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSgdgVAf7b23fba3Mb:-OBSgdgVAf7b23fba3Mc:bxs881q) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupE.ts#L25)):*
> ```XML
>       ? obj.xMun === "EXTERIOR" && obj.UF === "EX"
>       : true,
>   ) // TODO: cPais e xPais !== Brasil
> ```

Validação não legível. Use sugestões anteriores.
___
*[`src/dfe/nfe/schemas/groupE.ts` line 49 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSh9-N92G_CuYE7ftp:-OBSh9-N92G_CuYE7ftq:b-nsf2x1) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupE.ts#L49)):*
> ```XML
>       (obj.indIEDest === "1" ? obj.IE : true) && // 1=Contribuinte ICMS (informar a IE do destinatário);
>       (obj.indIEDest === "2" ? !obj.IE : true), // No caso de Contribuinte Isento de Inscrição (indIEDest=2), não informar a tag IE do destinatário
>   )
> ```

Não legível.
___
*[`src/dfe/nfe/schemas/groupE.ts` line 57 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBShCEZ0z6d4l5iHwTx:-OBShCEZ0z6d4l5iHwTy:undefined) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupE.ts#L57)):*
> ```XML
>  * @description Grupo E. Identificação do Destinatário da Nota Fiscal eletrônica
>  */
> export { schemaNfeDest, type NfeDest };
> ```





_Suggestion:_
```XML
/**
 * @description Grupo E. Identificação do Destinatário da Nota Fiscal eletrônica
 */
type NfeDest = z.infer<typeof schemaNfeDest>;

export { schemaNfeDest, type NfeDest };
```
___
*[`src/dfe/nfe/schemas/groupF.ts` line 20 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBShK342r9IN_n5qNjY:-OBShK342r9IN_n5qNjZ:undefined) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupF.ts#L20)):*
> ```XML
>     UF: zUf().or(z.literal("EX")).describe("F09"),
>     CEP: zCustom.string.numeric().length(8).optional().describe("F10"),
>     cPais: zCustom.string.numeric().length(4).optional().describe("F11"), // Utilizar a Tabela do BACEN (Seção 8.3 do MOC – Visão Geral,Tabela de UF, Município e País).
> ```





_Suggestion:_
```XML
    cPais: zCustom.string.numeric().length(4).optional().describe("F11"),
```
___
*[`src/dfe/nfe/schemas/groupF.ts` line 32 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBShS4lB2h7Vo2nRrj_:-OBShS4lB2h7Vo2nRrja:b-nsf2x1) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupF.ts#L32)):*
> ```XML
>         ? obj.cMun === "9999999" && obj.xMun === "EXTERIOR" && obj.UF === "EX"
>         : true),
>   )
> ```

Não legível.
___
*[`src/dfe/nfe/schemas/groupF.ts` line 40 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBShVhGAoMjk31bhUE1:-OBShVhGAoMjk31bhUE2:undefined) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupF.ts#L40)):*
> ```XML
>  * @description Grupo F. Identificação do Local de Retirada
>  */
> export { schemaNfeRetirada, type NfeRetirada };
> ```





_Suggestion:_
```XML
/**
 * @description Grupo F. Identificação do Local de Retirada
 */
type NfeRetirada = z.infer<typeof schemaNfeRetirada>;

export { schemaNfeRetirada, type NfeRetirada };
```
___
*[`src/dfe/nfe/schemas/groupC.ts` line 34 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSdXrY8Qx9XI7QPprw:-OBSdXrZ1mKaMwqpkfIL:bqhpf3q) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupC.ts#L34)):*
> ```XML
>     "SE",
>     "TO",
>   ]);
> ```

Aplique sugestão lá do grupo B pro código, para definir parecido aqui pro símbolo.
___
*[`src/dfe/nfe/schemas/groupC.ts` line 46 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSdkspDGt0kOi9yKhS:-OBSdkspDGt0kOi9yKhT:bphfcf6) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupC.ts#L46)):*
> ```XML
>   CEP: zCustom.string.numeric().length(8).optional().describe("C13"),
>   cPais: zCustom.string.numeric().length(4).optional().describe("C14"), // "1058" = Brasil
>   xPais: zCustom.string.range(2, 60).optional().describe("C15"), // "brasil" ou "BRASIL"
> ```

Coloque no `describe()` se relevante. E na verdade é "Brasil", não "brasil".
___
*[`src/dfe/nfe/schemas/groupC.ts` line 58 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSe9sZ8LU7f5vxuvCw:-OBSe9sZ8LU7f5vxuvCx:bcqum2x) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/dfe/nfe/schemas/groupC.ts#L58)):*
> ```XML
>     enderEmit: schemaEnderEmit.describe("C05"),
>     IE: zCustom.string.ie().describe("C17"),
>     IEST: zCustom.string.ie().optional().describe("C18"), // IE do Substituto Tributário
> ```

Comentário irrelevante.



_Suggestion:_
```XML
    IEST: zCustom.string.ie().optional().describe("C18"),
```
___
*[`src/dfe/nfe/s [...]

2024-11-12 00:45 UTC, gabrieljablonski commented on src/dfe/nfe/schemas/groupA.ts
> +      }),
Pequeno ajuste na sugestão do coelho.

```ts
      .refine((array) =>
        array.every(({ nItem }, i) => Number(nItem) === i + 1),
      ),
```
<!-- Reviewable comment -OBSR7zeDxLiKSPVKEfL:bkyspn5 -->
<!-- Sent from Reviewable.io -->

2024-11-12 00:45 UTC, gabrieljablonski commented on src/dfe/nfe/schemas/groupI.ts
> +  .refine((obj) => (obj.indEscala || obj.CNPJFab ? obj.CEST : true)) // Grupo Opcional (I05b)
^

Mas o do coelho tbm não ficou legal.
<!-- Reviewable comment -OBSkq0W1C0gtJF2hBLi:b-qzp166 -->
<!-- Sent from Reviewable.io -->

2024-11-12 00:45 UTC, gabrieljablonski commented on src/dfe/nfe/schemas/BA.ts
> +    .refine((value) => isValidAamm(value));
Aproveitando o bonde aqui do coelho.

Não precisa da função de validação separada, e coloca a mensagem.

E tbm não diria que é um schema, e sim um campo custom, então `zAAMM` ao invés de `schemaAAMM` acho que faz mais sentido.



_Suggestion (from src/dfe/nfe/schemas/groupBA.ts):_
```XML
const zAAMM = () =>
  zCustom.string
    .numeric()
    .length(4)
    .refine(
      (value) => {
        const month = Number(value.slice(2));
        return month >= 1 && month <= 12;
      },
      { message: "Mês deve ser entre 01 e 12." },
    );
```
<!-- Reviewable comment -OBSa40G5Mr33cYPvvba:brs1kyx -->
<!-- Sent from Reviewable.io -->

2024-11-12 00:45 UTC, gabrieljablonski commented on src/dfe/nfe/schemas/BA.ts
> +  .refine((obj) => zCustom.utils.hasOnlyOne([obj.CNPJ, obj.CPF]));
^
<!-- Reviewable comment -OBScoiX7OxvmL_PKN4y:b3ks9 -->
<!-- Sent from Reviewable.io -->

2024-11-12 00:45 UTC, gabrieljablonski commented on src/dfe/nfe/schemas/BA.ts
> +  )
^
<!-- Reviewable comment -OBSd807EP1YofuclQIy:b3ks9 -->
<!-- Sent from Reviewable.io -->

2024-11-25 22:57 UTC, gabrieljablonski requested changes
review parcial

> Reviewed 15 of 26 files at r8, all commit messages.
> Dismissed @coderabbitai[bot] from 22 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/29#-:-OC_Xla79MEBr9uBC7vF:barf6pb)* status: 18 of 31 files reviewed, 49 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])

___
*[`src/dfe/nfe/layoutNfe/groupB.ts` line 33 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_6P9V7eTtiY71HXtt:-OC_6P9W6TpBVT2NZl8X:b6pnvyl) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupB.ts#L33)):*
> ```XML
>       })
>       .optional()
>       .describe("B10"),
> ```

Essas validações não estão corretas para `dhEmi` e `dhSaiEnt`.

Veja página 76 do anexo I.

![image.png](https://files.reviewableusercontent.io/images/reviewable/21102974/cpBfBu6ZUbxZoso6jrsjANCV/image.png)

PORÉM, ignore B10-20 e B10-30 (nem todas as SEFAZ implementam dessa forma).

Implemente apenas B10-40 (`dhSaiEnt >= dhEmi`).
___
*[`src/dfe/nfe/layoutNfe/groupB.ts` line 51 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_7Q3c2SnGUiN-M1CD:-OC_7Q3c2SnGUiN-M1CE:b1oqc21) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupB.ts#L51)):*
> ```XML
>       .refine((date) => new Date(date) <= new Date(), {
>         message: "Data de emissão não pode ser futura",
>       })
> ```

Essa validação não existe.
___
*[`src/dfe/nfe/layoutNfe/groupB.ts` line 69 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_7c242-_j32aaGnzX:-OC_7c25CSJlO3s1k2eM:be7lfur) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupB.ts#L69)):*
> ```XML
>     },
>   )
>   .refine(({ cNF, nNF }) => cNF !== nNF, {
> ```

Considere a seguinte situação:

- `cNF: "00000001"`
- `nNF: "1"`

Ambos os campos estão preenchidos corretamente segundo os tipos de cada um, porém `cNF` é inválido (essa validação não aponta isso).
___
*[`src/dfe/nfe/layoutNfe/groupBA.ts` line 23 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_93n8D6wA0lHlbvUU:-OC_93n8D6wA0lHlbvUV:b6awxk6) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupBA.ts#L23)):*
> ```XML
>     .min(1)
>     .max(9)
>     .refine((value) => Number(value) > 0);
> ```

`zSerie` e `zNnf` nem são tão complexos, e são usados apenas 2x cada. Remova essas definições, só achei que ficou mais complicado.

E pra simplificar, pode remover esse `refine()` também.
___
*[`src/dfe/nfe/layoutNfe/groupA.ts` line 51 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_3BrS8PRs7tV4E02p:-OC_3BrS8PRs7tV4E02q:bimjh2p) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupA.ts#L51)):*
> ```XML
>       }
>       return true;
>     },
> ```

Duas coisas:

1. Não sei se fui eu que sugeri assim, mas evite "destructuring" aninhado. Fica difícil de ler.
2. A sugestão do if/else era só pra verificações mais complexas. Essa é bem linear, então o ternário funciona bem.
3. Use `!!` ao invés de checks explicítos.



_Suggestion:_
```XML
    ({ ide, dest }) => ide.mod === "55" ? !!dest.xNome : true,
```
___
*[`src/dfe/nfe/layoutNfe/groupA.ts` line 62 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_4SUU-J-BhAszrTzi:-OC_4SUU-J-BhAszrTzj:b-fj5p1f) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupA.ts#L62)):*
> ```XML
>       }
>       return true;
>     },
> ```

Mesmo de cima.



_Suggestion:_
```XML
    ({ ide, dest }) =>
      ide.mod === "65" ? dest.indIEDest === "9" && !dest.IE : true,
```
___
*[`src/dfe/nfe/layoutNfe/groupI.ts` line 69 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_Ct9Q8sSJNd4tr03R:-OC_Ct9Q8sSJNd4tr03S:bg1x3d5) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupI.ts#L69)):*
> ```XML
>       }
>       return true;
>     },
> ```

Mudei de ideia sobre esse aqui. Acho que sem o `obj.` de prefixo, pode deixar o ternário mesmo.



_Suggestion:_
```XML
    ({ indEscala, CNPJFab, CEST }) => (indEscala || CNPJFab ? !!CEST : true),
```
___
*[`src/dfe/nfe/layoutNfe/groupE.ts` line 63 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_AciX6-qBPscjyGPf:-OC_AciX6-qBPscjyGPg:undefined) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupE.ts#L63)):*
> ```XML
>       }
>       return true;
>     },
> ```





_Suggestion:_
```XML
    ({ idEstrangeiro, enderDest }) =>
      idEstrangeiro ? enderDest.xMun === "EXTERIOR" : true,
```


<!-- Sent from Reviewable.io -->

2024-11-25 22:57 UTC, gabrieljablonski commented on src/dfe/nfe/layoutNfe/groupA.ts
> +      }),
Coelho está correto, mas sugiro corrigir assim:



_Suggestion:_
```XML
      .refine((array) => array.every(({ nItem }, i) => Number(nItem) === i + 1)),
```
<!-- Reviewable comment -OC_1qdmC_NDe6ORkJWx:bhaueg -->
<!-- Sent from Reviewable.io -->

2024-11-25 22:57 UTC, gabrieljablonski commented on src/dfe/nfe/layoutNfe/groupI.ts
> +      .describe("I15"),
^

O anexo I tá doido, tem isso aqui não.
<!-- Reviewable comment -OC_BzyH6WJ3mP9yQxij:benn5h2 -->
<!-- Sent from Reviewable.io -->

2024-11-27 06:55 UTC, CayoPOliveira reviewed
-(question/changes requested) +(review needed) 

> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/29#-:-OCgOKSt46x4vn-Pbg4i:b-dsi9wo)* status: 18 of 31 files reviewed, 37 unresolved discussions (waiting on @CayoPOliveira, @coderabbitai[bot], @gabrieljablonski, and @throws)

___
*[`src/utils/zCustom.ts` line 7 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSoKUaAPbicfvKkYTb:-OCgOASIB8Vb2n7HK-vN:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/utils/zCustom.ts#L7)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Acho que o nome correto dessa função seria `length`. `range` é mais pra quando estamos tratando especificamente de números.

Por exemplo, `range(1, 1000)` -> número entre 1 e 1000.
</blockquote></details>

Done.
___
*[`src/utils/zCustom.ts` line 7 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSlWuoBOEQo8ZDrdja:-OCgOCk17T8ecH25EhvU:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/utils/zCustom.ts#L7)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Precisa desses prefixos `string*` nos tipos custom?

Pq não só `range`?
</blockquote></details>

Done.
___
*[`src/utils/zCustom.ts` line 9 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSlIOoBiEPDIgi9hTY:-OCgFKXK2AOdkdmcy1yZ:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/utils/zCustom.ts#L9)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Mensagens de validação em português.
</blockquote></details>

Done.
___
*[`src/utils/zCustom.ts` line 16 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSlfOg5DdKrCTndp2C:-OCgFYMUEl2EmgwwBn1H:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/utils/zCustom.ts#L16)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Não está legal essa definição de `decimal`.

1. Veja XMLs de exemplo, o separador é sempre `.`, não `,`.

2. A definição acaba precisando utilizar ainda o `min()` e o `max()`.

Na documentação, onde consta `13v2`, deve ser represetado como `decimal(13, 2)`.

E para simplificar, quando varia a quantidade de casas decimais: `11v0-10` -> `decimal(11, 10)`.
</blockquote></details>

Done.
___
*[`src/utils/zCustom.ts` line 32 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSmRKQBfu52XkdonWK:-OCgFqhTC3VLIJ_SwSQF:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/utils/zCustom.ts#L32)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

A validação aqui deve ser 100% responsabilidade das funções de validação.
</blockquote></details>

Done.
___
*[`src/utils/zCustom.ts` line 45 at r4](https://reviewable.io/reviews/fazendatech/brafis/29#-OBSmooyEQipOjxTQz6e:-OCgKVAZ2QFde_tTnAXV:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/0e8c4858563c18836c01dd909a0bcecb77b62ca2/src/utils/zCustom.ts#L45)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

1. Implementar testes. Tem um bug seríssimo nessas implementações.

2. Essas funções não servem para validar args como número 0, false, string vazia, etc...

3. Use "rest params", tipo

```ts
function hasOnlyOne(...values: unknown[])
```

PS.: Isso vai quebrar os usos atuais, mas não vai dar erro de compilação. Refatorar com cuidado.

4. Generics só devem ser usados quando estritamente necessário. Como sugerido acima, usar `unknown` quando não fizer diferença.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layoutNfe/groupA.ts` line 51 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_3BrS8PRs7tV4E02p:-OCfBIPe0IniXYasZ-U5:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupA.ts#L51)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Duas coisas:

1. Não sei se fui eu que sugeri assim, mas evite "destructuring" aninhado. Fica difícil de ler.
2. A sugestão do if/else era só pra verificações mais complexas. Essa é bem linear, então o ternário funciona bem.
3. Use `!!` ao invés de checks explicítos.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layoutNfe/groupA.ts` line 62 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_4SUU-J-BhAszrTzi:-OCfBIwu0uBNHNJZVWnj:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupA.ts#L62)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Mesmo de cima.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layoutNfe/groupB.ts` line 33 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_6P9V7eTtiY71HXtt:-OCfERPn8FGkWQtZM89O:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupB.ts#L33)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Essas validações não estão corretas para `dhEmi` e `dhSaiEnt`.

Veja página 76 do anexo I.

![image.png](https://files.reviewableusercontent.io/images/reviewable/21102974/cpBfBu6ZUbxZoso6jrsjANCV/image.png)

PORÉM, ignore B10-20 e B10-30 (nem todas as SEFAZ implementam dessa forma).

Implemente apenas B10-40 (`dhSaiEnt >= dhEmi`).
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layoutNfe/groupB.ts` line 51 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_7Q3c2SnGUiN-M1CD:-OCfFmPpANd3ccKDfXrc:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupB.ts#L51)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Essa validação não existe.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layoutNfe/groupB.ts` line 69 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_7c242-_j32aaGnzX:-OCfFxX14QpghpS14JlS:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupB.ts#L69)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Considere a seguinte situação:

- `cNF: "00000001"`
- `nNF: "1"`

Ambos os campos estão preenchidos corretamente segundo os tipos de cada um, porém `cNF` é inválido (essa validação não aponta isso).
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layoutNfe/groupBA.ts` line 23 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_93n8D6wA0lHlbvUU:-OCfMMVA9hrFDf7JC7Ps:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupBA.ts#L23)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

`zSerie` e `zNnf` nem são tão complexos, e são usados apenas 2x cada. Remova essas definições, só achei que ficou mais complicado.

E pra simplificar, pode remover esse `refine()` também.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layoutNfe/groupI.ts` line 69 at r8](https://reviewable.io/reviews/fazendatech/brafis/29#-OC_Ct9Q8sSJNd4tr03R:-OCg70PcCY_5eO3KPWXE:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/f75170f7b57c8bed3eda510182b8479b5fe5275d/src/dfe/nfe/layoutNfe/groupI.ts#L69)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Mudei de ideia sobre esse aqui. Acho que sem o `obj.` de prefixo, pode  [...]

2024-11-27 06:55 UTC, CayoPOliveira commented on src/utils/zCustom.ts
> +}
Done.
<!-- Reviewable comment -OCgKhFYBB6ft4YyjZGN:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-11-27 06:55 UTC, CayoPOliveira commented on src/dfe/nfe/layoutNfe/groupA.ts
> +      }),
Done.
<!-- Reviewable comment -OCfAePN0I_zVRH3U1uc:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-11-27 06:55 UTC, CayoPOliveira commented on src/dfe/nfe/layoutNfe/groupI.ts
> +      .describe("I15"),
Fiquei confuso, quis dizer que não tem o "SEM GTIN"? Removi ele.
<!-- Reviewable comment -OCg6IgE9rHBTQZ0GXzp:baqueed -->
<!-- Sent from Reviewable.io -->

2024-11-27 06:55 UTC, CayoPOliveira commented on src/dfe/nfe/schemas/C.ts
> +});
Done Usei a sugestão de validação.
<!-- Reviewable comment -OCfmiLJD05QFGRfZhIe:brqjbu8 -->
<!-- Sent from Reviewable.io -->

2024-11-27 06:55 UTC, CayoPOliveira commented on src/dfe/nfe/schemas/groupB.ts
> +    nNF: zCustom.string.numeric().min(1).max(9).describe("B08"),
@gabrieljablonski  A sugestão do coelho não é necessária, pelo menos no documento não existe essa regra, porém, o `nNF` pode usar a mesma função `invalidCnfs()`?
<!-- Reviewable comment -OCfBzrAA355Ag5QMF9U:b-jgwflk -->
<!-- Sent from Reviewable.io -->

2024-11-27 06:55 UTC, CayoPOliveira commented on src/dfe/nfe/schemas/groupY.ts
> +        vLiq: zCustom.string.decimal().length(16).optional().describe("Y06"),
Done Resolvido com a mudança da implementação do `zCustom.string.decimal()`
<!-- Reviewable comment -OCgBEbs7gXmDVKrSfVi:bdwgo20 -->
<!-- Sent from Reviewable.io -->

2024-11-27 12:02 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/29)* status: 2 of 31 files reviewed, 46 unresolved discussions (waiting on @coderabbitai[bot], @gabrieljablonski, and @throws)



<!-- Sent from Reviewable.io -->

2024-11-27 12:02 UTC, CayoPOliveira commented on src/dfe/nfe/layoutNfe/groupBA.ts
> +          .describe("BA09"),
o .min(1) não evita o valor "0", ele é para evitar string vazia, sendo outro caso que não está permitido para esse campo
<!-- Reviewable comment -OChS4VC2x09dq0-ucIz:bkocron -->
<!-- Sent from Reviewable.io -->

2024-11-27 12:02 UTC, CayoPOliveira commented on src/dfe/nfe/layoutNfe/groupI01.ts
> +            .describe("I29a"),
Done.
<!-- Reviewable comment -OChTG7O2wqcjmya3EzB:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-11-27 12:02 UTC, CayoPOliveira commented on src/dfe/nfe/layoutNfe/groupI01.ts
> +    },
Done. A mensagem que estava errada
<!-- Reviewable comment -OChThAu8klotVBJvqSl:b3qnhmf -->
<!-- Sent from Reviewable.io -->

2024-11-27 13:42 UTC, gabrieljablonski approved these changes

2024-11-27 13:43 UTC, merged