Feat signed nfe xml
fazendatech/brafis pull request #32
Opened 2024-12-11 13:08 UTC by CayoPOliveira

2024-12-11 16:09 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/32)* status: 0 of 32 files reviewed, 5 unresolved discussions (waiting on @coderabbitai[bot] and @gabrieljablonski)



<!-- Sent from Reviewable.io -->

2024-12-11 16:09 UTC, CayoPOliveira commented on src/dfe/nfe/layout/index.ts
> +  });
@coderabbitai[bot] Ignore isso, esse é o padrão e regras do SEFAZ
<!-- Reviewable comment -ODqStUT-9cR5DwGJ7dO:b-i1vv1r -->
<!-- Sent from Reviewable.io -->

2024-12-11 16:09 UTC, CayoPOliveira commented on src/dfe/nfe/layout/index.ts
> +    digestAlgorithm: "http://www.w3.org/2000/09/xmldsig#sha1",
@coderabbitai[bot] Ignore isso, esse é o padrão e regras do SEFAZ
<!-- Reviewable comment -ODqTXPO1_al03v1QnW2:b-i1vv1r -->
<!-- Sent from Reviewable.io -->

2024-12-11 16:09 UTC, CayoPOliveira commented on src/dfe/nfe/layout/index.ts
> +  });
@gabrieljablonski O que acha? Devo voltar a definição do uri?
<!-- Reviewable comment -ODqTbv75XUSWYbFPHMP:buufy5r -->
<!-- Sent from Reviewable.io -->

2024-12-11 16:09 UTC, CayoPOliveira commented on src/dfe/nfe/layout/index.test.ts
> +      ).asPem();
@coderabbitai[bot] São arquivos de teste, pode ignorar
<!-- Reviewable comment -ODqTo1r0ohr-QAkZTvZ:b-b519ck -->
<!-- Sent from Reviewable.io -->

2024-12-11 16:09 UTC, CayoPOliveira commented on src/dfe/nfe/layout/groupM.ts
> +    ICMS: schemaNfeIcms,
Corrigi na branch mesmo, o `schemaNfeIcms` era chamado de `schemaNfeICMS`, alterei apenas ele mas fiquei na duvida se alterava por exemplo o `schemaNfeICMS00` para o padrão

@gabrieljablonski qual a sua opinião?
<!-- Reviewable comment -ODqSSjc1_4A3_SoazCp:b-r7utfh -->
<!-- Sent from Reviewable.io -->

2024-12-11 21:07 UTC, gabrieljablonski requested changes
Aproveitando a oportunidade, atualizar schema do `consultaCadastro` para incluir mensagem do `refine` tbm.

https://github.com/fazendatech/brafis/blob/27adaab2fb40ac3f0d1d799633f36281d2b29790/src/dfe/nfe/webServices/requests/consultaCadastro.ts#L10-L16

+(question/changes requested) 

> Reviewed 32 of 32 files at r1, all commit messages.
> Dismissed @CayoPOliveira and @coderabbitai[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/32#-:-ODr5v3h5mfk0Y0HicIw:b-de88xm)* status: all files reviewed, 14 unresolved discussions (waiting on @CayoPOliveira and @coderabbitai[bot])

___
*[`src/dfe/nfe/layout/index.ts` line 14 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODr779f-cCid2QNfIyp:-ODr779f-cCid2QNfIyq:undefined) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L14)):*
> ```XML
> 
> /**
>  * @description Gera o XML assinado da NFe a partir do schema implementado com zod.
> ```





_Suggestion:_
```XML
 * @description Gera o XML assinado da NFe.
```
___
*[`src/dfe/nfe/layout/index.ts` line 16 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODr6uQPATSr6FujaoNq:-ODr6uQPATSr6FujaoNr:b-aa2ake) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L16)):*
> ```XML
>  * @description Gera o XML assinado da NFe a partir do schema implementado com zod.
>  */
> export function signNfe(
> ```

Eu não acho que faz sentido essa função estar definida aqui no `layout/index.ts`.

`layout` deve conter apenas as informações de schema. A assinatura do XML é um serviço independente.
___
*[`src/dfe/nfe/layout/index.ts` line 17 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrT9fbAEfQ918ut8Wd:-ODrT9fbAEfQ918ut8We:bln1zh3) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L17)):*
> ```XML
>  */
> export function signNfe(
>   nfeData: NfeInfNfe,
> ```

Nome melhor compatível com o contexto.



_Suggestion:_
```XML
  infNfe: NfeInfNfe,
```
___
*[`src/dfe/nfe/layout/index.ts` line 18 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODr6bU9-FhUuv5PjYV4:-ODr6bU9-FhUuv5PjYV5:bdo97rz) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L18)):*
> ```XML
> export function signNfe(
>   nfeData: NfeInfNfe,
>   { privateKey, publicCert }: SignNfeInfo,
> ```

Por que não usar a classe `CertificateP12` como argumento?
___
*[`src/dfe/nfe/layout/index.ts` line 26 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrT0O894cnjoYIjjZl:-ODrT0O99HM0sWhUVMwJ:bvgqu1w) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L26)):*
> ```XML
>     attributeNamePrefix: "@_",
>   });
>   const xml = builder.build({ NFe: nfeData });
> ```

Estrutura do XML está sendo montada incorretamente. Compare com atenção com XML de nota real.
___
*[`src/dfe/nfe/layout/groupA.ts` line 29 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODr5aDc-pLFev1uHBHC:-ODr5aDc-pLFev1uHBHD:b-84dcks) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/groupA.ts#L29)):*
> ```XML
>       .length(47)
>       .refine((value) => isValidAccessCode(value.slice(3), { strict: true }), {
>         message: "O Id da nota está em formato invalido.",
> ```

NIT



_Suggestion:_
```XML
        message: "O Id da nota está em formato inválido.",
```
___
*[`src/dfe/nfe/layout/index.test.ts` line 299 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrTtisBStnyCg6rl7Z:-ODrTtisBStnyCg6rl7_:b-mygct) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L299)):*
> ```XML
>         "123456789012345678901234567890123456789012345678901234567890",
>     },
>     infAdic: {},
> ```

Esse é fácil de adicionar um exemplo, e é um campo bastante utilizado. Coloca dados de teste para `infAdFisco` e `infCpl` por favor.
___
*[`src/dfe/nfe/layout/index.test.ts` line 319 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrVhmc2FrBq_CjzP3Z:-ODrVhmc2FrBq_CjzP3_:b-pii6gv) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L319)):*
> ```XML
>       });
>     });
>     describe("groupBA", () => {
> ```

Não acha que fica visualmente menos carregado separando os describes?



_Suggestion:_
```XML
  describe("zod schemas", () => {
    describe("groupA", () => {
      test("Returns success for a valid infNfe schema", () => {
        expect(() => schemaNfeInfNfe.parse(validNfe)).not.toThrow(ZodError);
      });
    });

    describe("groupB", () => {
      test("Returns success for a valid ide schema", () => {
        expect(() => schemaNfeIde.parse(validNfe.ide)).not.toThrow(ZodError);
      });
    });

    describe("groupBA", () => {
```
___
*[`src/dfe/nfe/layout/index.test.ts` line 325 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrVLfJDyHeoV4uDr2_:-ODrVLfJDyHeoV4uDr2a:b-h54pqh) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L325)):*
> ```XML
>         });
>       }
>     });
> ```

Esse pattern de testes deve ser evitado quando possível, mas acho que cabe ter aqui, pois os objetos `NFref` podem ter formatos diferentes.

Porém, sugiro não criar testes com nomes idênticos. Fica mais difícil de debugar.



_Suggestion:_
```XML
    describe("groupBA", () => {
      const arrayNFref = validNfe.ide.NFref ?? [];

      for (const [i, NFref] of arrayNFref.entries()) {
        test(`Returns success for a valid NFref schema ${i + 1}`, () => {
          expect(() => schemaNfeNfRef.parse(NFref)).not.toThrow(ZodError);
        });
      }
    });
```
___
*[`src/dfe/nfe/layout/index.test.ts` line 362 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrW98hAriuROfVWV_1:-ODrW98i8JcSCRgVQNZ1:b4f1jxw) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L362)):*
> ```XML
>           expect(() => schemaNfeAutXml.parse(autXML)).not.toThrow(ZodError);
>         });
>       }
> ```

Remover `for` e aplicar somente para o primeiro (único) elemento.

Aplicar para todos os grupos abaixo.



_Suggestion:_
```XML
      test("Returns success for a valid autXML schema", () => {
        expect(() => schemaNfeAutXml.parse(validNfe.autXML?.[0])).not.toThrow(
          ZodError,
        );
      });
```
___
*[`src/dfe/nfe/layout/index.test.ts` line 486 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrWaVx25Rl4NEyL3S9:-ODrWaVx25Rl4NEyL3SA:btxk9dw) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L486)):*
> ```XML
>   });
> 
>   describe("generateAndSignNfe", () => {
> ```

Lembrando que a função `signNfe` não faz sentido estar no módulo `layout`, então esse teste deverá ser movido (e o `describe` não está com o nome da função).
___
*[`src/dfe/nfe/layout/index.test.ts` line 493 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrXATI5EEdjWol9brJ:-ODrXATI5EEdjWol9brK:b-h3t1ic) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L493)):*
> ```XML
>           password: process.env.TEST_CERTIFICATE_PASSWORD ?? "",
>         })
>       ).asPem();
> ```

Essas variáveis não estavam sendo usadas para o certificado de teste real (felippe)? Você atualizou no seu ambiente local para o certificado "falso"?

Não faz sentido apontar pro certificado de teste com variável de ambiente, já que o objetivo é que esse certificado esteja disponível para todos os mód [...]

2024-12-11 21:07 UTC, gabrieljablonski commented on src/dfe/nfe/layout/index.ts
> +  });
Sugiro atualizar o `xpath` pra ficar mais rigoroso.

Tradução:

- `/` - raiz do XML
- `NFe` - a tag
- `[@Id='...']` - com atributo `Id` igual ao valor



_Suggestion:_
```XML
  sig.addReference({
    xpath: `/NFe[@Id='${nfeData["@_Id"]}']`,
    transforms: [
      "http://www.w3.org/2000/09/xmldsig#enveloped-signature",
      "http://www.w3.org/TR/2001/REC-xml-c14n-20010315",
    ],
    digestAlgorithm: "http://www.w3.org/2000/09/xmldsig#sha1",
  });
```
<!-- Reviewable comment -ODrRfko0damIgEc7yCM:buevfmn -->
<!-- Sent from Reviewable.io -->

2024-12-11 21:07 UTC, gabrieljablonski commented on src/dfe/nfe/layout/groupM.ts
> +    ICMS: schemaNfeIcms,
> fiquei na duvida se alterava por exemplo o `schemaNfeICMS00` para o padrão

Se for fácil pode alterar
<!-- Reviewable comment -ODr6Mj1CVLtY74_fsBS:br5jrv7 -->
<!-- Sent from Reviewable.io -->

2024-12-13 02:38 UTC, CayoPOliveira reviewed
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/32)* status: all files reviewed, 10 unresolved discussions (waiting on @coderabbitai[bot], @gabrieljablonski, and @id)

___
*[`src/dfe/nfe/layout/index.ts` line 16 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODr6uQPATSr6FujaoNq:-ODwGZJx-tOyUXF5XHKR:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L16)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Eu não acho que faz sentido essa função estar definida aqui no `layout/index.ts`.

`layout` deve conter apenas as informações de schema. A assinatura do XML é um serviço independente.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layout/index.ts` line 18 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODr6bU9-FhUuv5PjYV4:-ODwG_-QBUbTik4c1Iuc:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L18)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Por que não usar a classe `CertificateP12` como argumento?
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layout/index.ts` line 26 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrT0O894cnjoYIjjZl:-ODwG_j0B9UQRuvhv6hZ:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.ts#L26)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Estrutura do XML está sendo montada incorretamente. Compare com atenção com XML de nota real.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layout/index.test.ts` line 299 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrTtisBStnyCg6rl7Z:-ODwJwlOB56Y2QOPqGyf:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L299)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Esse é fácil de adicionar um exemplo, e é um campo bastante utilizado. Coloca dados de teste para `infAdFisco` e `infCpl` por favor.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layout/index.test.ts` line 362 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrW98hAriuROfVWV_1:-ODxpm1W3RmBm_grrNrz:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L362)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Remover `for` e aplicar somente para o primeiro (único) elemento.

Aplicar para todos os grupos abaixo.
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layout/index.test.ts` line 486 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrWaVx25Rl4NEyL3S9:-ODxpx-DEgTH6de3XB5u:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L486)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Lembrando que a função `signNfe` não faz sentido estar no módulo `layout`, então esse teste deverá ser movido (e o `describe` não está com o nome da função).
</blockquote></details>

Done.
___
*[`src/dfe/nfe/layout/index.test.ts` line 493 at r1](https://reviewable.io/reviews/fazendatech/brafis/32#-ODrXATI5EEdjWol9brJ:-ODxs4NMCrC17hNhGU2L:b-896fix) ([raw file](https://github.com/fazendatech/brafis/blob/13677093bcb0e23f41860b350f8f4ba902734d4d/src/dfe/nfe/layout/index.test.ts#L493)):*
<details><summary><i>Previously, gabrieljablonski (Gabriel Jablonski) wrote…</i></summary><blockquote>

Essas variáveis não estavam sendo usadas para o certificado de teste real (felippe)? Você atualizou no seu ambiente local para o certificado "falso"?

Não faz sentido apontar pro certificado de teste com variável de ambiente, já que o objetivo é que esse certificado esteja disponível para todos os módulos para os testes.

Pode usar o caminho "hardcoded", pq o arquivo é uma dependência direta, assim como arquivos de código normal mesmo.

`misc/sample-certificates/cert.pfx`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-13 02:38 UTC, CayoPOliveira commented on src/dfe/nfe/layout/index.ts
> +  });
Teste usar dessa forma, porém não funcionou.
```xpath: `/NFe[@Id='${nfe.NFe.infNFe["@_Id"]}']`,```
<!-- Reviewable comment -ODwHRV_7ZS8b2TbtO95:bz9hawy -->
<!-- Sent from Reviewable.io -->

2024-12-13 02:38 UTC, CayoPOliveira commented on src/dfe/nfe/layout/groupM.ts
> +    ICMS: schemaNfeIcms,
Done.
<!-- Reviewable comment -ODshppeA0OM80eHmtsB:b-896fix -->
<!-- Sent from Reviewable.io -->

2024-12-13 12:48 UTC, gabrieljablonski approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

-(question/changes requested) +(approved for merge) 

> Reviewed 10 of 10 files at r2, 1 of 1 files at r3.
> Dismissed @CayoPOliveira and @coderabbitai[bot] from 5 discussions.
> *[Reviewable](https://reviewable.io/reviews/fazendatech/brafis/32#-:-OE-33U9Bt834FZUxWYz:b-ptdr55)* status: 31 of 35 files reviewed, all discussions resolved (waiting on @CayoPOliveira)



<!-- Sent from Reviewable.io -->

2024-12-13 12:49 UTC, merged